import { defineMessages, type MessageDescriptor } from "react-intl";
import {
  atSignLight16,
  atSignLight20,
  chatBubbleLight16,
  chatBubbleLight20,
  chatBubbleOnChatBubbleLight16,
  chatBubbleOnChatBubbleLight20,
  checkmarkSquareLight16,
  checkmarkSquareLight20,
  clipboardListLight16,
  clipboardListLight20,
  codeLight16,
  codeLight20,
  linkLight16,
  linkLight20,
  listBulletLight16,
  listBulletLight20,
  listNumberLight16,
  listNumberLight20,
  magicWandLight16,
  magicWandLight20,
  minusMdLight16,
  minusMdLight20,
  paperclipLight16,
  paperclipLight20,
  photoLight16,
  photoLight20,
  playCircleLight16,
  playCircleLight20,
  quotemarkLight16,
  quotemarkLight20,
  shapesLight16,
  shapesLight20,
  slidesLight16,
  slidesLight20,
  spreadsheetLight16,
  spreadsheetLight20,
  squareTextFormatLight16,
  squareTextFormatLight20,
  stickyNotesLight16,
  stickyNotesLight20,
  tableLight16,
  tableLight20,
  tableColumnLight16,
  tableColumnLight20,
  textPageLight16,
  textPageLight20,
  textStyleSmLight16,
  textStyleSmLight20,
  trashLight16,
  trashLight20,
} from "../../codex/icons";
import type { SizedIconSource } from "../../codex/ui";

export type SlashSection = "create" | "generate" | "generatePrompt" | "basic" | "media" | "mentioned" | "table";

export interface SlashCommand {
  id: string;
  icon: SizedIconSource;
  label: MessageDescriptor;
  description?: MessageDescriptor;
  section: SlashSection;
  keywords: string;
  shortcut?: string;
  /** Prefixes that turn the rest of the query into a prompt ("visualize a funnel"). */
  commands?: string[];
  /** Editable prompt starter for the query-only visualization variants. */
  prompt?: MessageDescriptor;
}

/** `oL`: section headings in the slash and insert menus. */
export const slashSectionMessages = defineMessages({
  create: { id: "codex.space.page.slashMenu.create", defaultMessage: "Create", description: "Section heading for creating child Pages and artifacts in the Page editor menu" },
  generate: { id: "codex.space.page.slashMenu.generateOptionsSection", defaultMessage: "Generate", description: "Section heading for text and visualization generation commands in the Page editor menu" },
  generatePrompt: { id: "codex.space.page.slashMenu.generateSection", defaultMessage: "Use your prompt", description: "Section for submitting the typed slash query as a generation request" },
  basic: { id: "codex.space.page.slashMenu.basicBlocks", defaultMessage: "Basic", description: "Section heading for basic content blocks in the Page slash menu" },
  media: { id: "codex.space.page.slashMenu.media", defaultMessage: "Media", description: "Section heading for image and file uploads in the Page slash menu" },
  mentioned: { id: "codex.space.page.slashMenu.mentioned", defaultMessage: "Mentioned", description: "Section heading for inserting file, Page, and chat references in the Page slash menu" },
  table: { id: "codex.space.page.slashMenu.tableActions", defaultMessage: "Table", description: "Section heading for table column actions in the Page slash menu" },
});

/** `aL` in the page content chunk, in menu order. */
export const slashCommands: SlashCommand[] = [
  {
    id: "agentInstructions",
    icon: { assets: { 16: clipboardListLight16, 20: clipboardListLight20 } },
    label: { id: "codex.space.page.actions.agentInstructions", defaultMessage: "Assistant instructions", description: "Page action that inserts a dedicated Agent Instructions block into a shared Page" },
    description: { id: "codex.space.page.actions.agentInstructionsDescription", defaultMessage: "Guide assistants on this page", description: "Supporting text in the Page insert menu for adding an Agent Instructions block" },
    section: "basic",
    keywords: "assistant agent instructions rules guidance",
  },
  {
    id: "page",
    icon: { assets: { 16: textPageLight16, 20: textPageLight20 } },
    label: { id: "codex.space.page.slashMenu.page", defaultMessage: "Page", description: "Page editor slash-menu action that creates a child Page and inserts its link" },
    description: { id: "codex.space.page.slashMenu.pageDescription", defaultMessage: "Create a page inside this one", description: "Supporting text in the Page editor slash menu for creating a child Page and inserting its link" },
    section: "create",
    keywords: "create new subpage sub-page child page",
  },
  {
    id: "spreadsheet",
    icon: { assets: { 16: spreadsheetLight16, 20: spreadsheetLight20 } },
    label: { id: "codex.space.page.slashMenu.createSpreadsheet", defaultMessage: "Sheet", description: "Page editor menu action that creates a spreadsheet" },
    description: { id: "codex.space.page.slashMenu.spreadsheetDescription", defaultMessage: "Work with data and formulas", description: "Supporting text in the Page editor slash menu for creating a spreadsheet with the Spreadsheets plugin" },
    section: "create",
    keywords: "create spreadsheets workbook excel xlsx",
  },
  {
    id: "presentation",
    icon: { assets: { 16: slidesLight16, 20: slidesLight20 } },
    label: { id: "codex.space.page.slashMenu.createPresentation", defaultMessage: "Slide", description: "Page editor menu action that creates a presentation" },
    description: { id: "codex.space.page.slashMenu.presentationDescription", defaultMessage: "Build a slide deck", description: "Supporting text in the Page editor slash menu for creating a presentation with the Presentations plugin" },
    section: "create",
    keywords: "create presentations slides deck powerpoint pptx",
  },
  {
    id: "canvas",
    icon: { assets: { 16: stickyNotesLight16, 20: stickyNotesLight20 } },
    label: { id: "pages.canvas.slash.label", defaultMessage: "Canvas", description: "Create a native Canvas embedded in this Page" },
    description: { id: "pages.canvas.slash.description", defaultMessage: "Create a canvas, or describe what to draw", description: "Canvas slash command creates an empty canvas or generates from the supplied prompt" },
    section: "create",
    keywords: "canvas board whiteboard draw diagram",
    commands: ["canvas"],
  },
  {
    id: "heading1",
    icon: { assets: { 16: textStyleSmLight16, 20: textStyleSmLight20 } },
    label: { id: "codex.space.page.slashMenu.heading1", defaultMessage: "Heading 1", description: "Page editor slash-menu action that inserts a level-one heading" },
    description: { id: "codex.space.page.slashMenu.heading1Description", defaultMessage: "Big section heading", description: "Supporting text in the Page editor slash menu for inserting a level-one heading" },
    section: "basic",
    keywords: "heading 1 h1",
    shortcut: "#",
  },
  {
    id: "heading2",
    icon: { assets: { 16: textStyleSmLight16, 20: textStyleSmLight20 } },
    label: { id: "codex.space.page.slashMenu.heading2", defaultMessage: "Heading 2", description: "Page editor slash-menu action that inserts a level-two heading" },
    description: { id: "codex.space.page.slashMenu.heading2Description", defaultMessage: "Medium section heading", description: "Supporting text in the Page editor slash menu for inserting a level-two heading" },
    section: "basic",
    keywords: "heading 2 h2",
    shortcut: "##",
  },
  {
    id: "heading3",
    icon: { assets: { 16: textStyleSmLight16, 20: textStyleSmLight20 } },
    label: { id: "codex.space.page.slashMenu.heading3", defaultMessage: "Heading 3", description: "Page editor slash-menu action that inserts a level-three heading" },
    description: { id: "codex.space.page.slashMenu.heading3Description", defaultMessage: "Small section heading", description: "Supporting text in the Page editor slash menu for inserting a level-three heading" },
    section: "basic",
    keywords: "heading 3 h3",
    shortcut: "###",
  },
  {
    id: "unorderedList",
    icon: { assets: { 16: listBulletLight16, 20: listBulletLight20 } },
    label: { id: "codex.space.page.slashMenu.unorderedList", defaultMessage: "Bulleted list", description: "Page editor slash-menu action that inserts a bulleted list" },
    description: { id: "codex.space.page.slashMenu.unorderedListDescription", defaultMessage: "Organize ideas in a simple list", description: "Supporting text in the Page editor slash menu for inserting a bulleted list" },
    section: "basic",
    keywords: "bulleted list unordered bullets",
    shortcut: "-",
  },
  {
    id: "orderedList",
    icon: { assets: { 16: listNumberLight16, 20: listNumberLight20 } },
    label: { id: "codex.space.page.slashMenu.orderedList", defaultMessage: "Numbered list", description: "Page editor slash-menu action that inserts a numbered list" },
    description: { id: "codex.space.page.slashMenu.orderedListDescription", defaultMessage: "An ordered list", description: "Supporting text in the Page editor slash menu for inserting a numbered list" },
    section: "basic",
    keywords: "numbered list ordered numbers",
    shortcut: "1.",
  },
  {
    id: "task",
    icon: { assets: { 16: playCircleLight16, 20: playCircleLight20 } },
    label: { id: "codex.space.page.slashMenu.task", defaultMessage: "Task", description: "Page slash command that inserts an editable action item with an explicit button to start a Codex task" },
    description: { id: "codex.space.page.slashMenu.taskDescription", defaultMessage: "Add an action to start with Willow", description: "Supporting text in the Page editor slash menu for inserting an editable action item with a button to start a Codex task" },
    section: "basic",
    keywords: "task action item follow up",
  },
  {
    id: "checklist",
    icon: { assets: { 16: checkmarkSquareLight16, 20: checkmarkSquareLight20 } },
    label: { id: "codex.space.page.slashMenu.checklist", defaultMessage: "Checklist", description: "Page editor slash-menu action that inserts a checkbox task list" },
    description: { id: "codex.space.page.slashMenu.checklistDescription", defaultMessage: "Track your to-dos", description: "Supporting text in the Page editor slash menu for inserting a checklist with checkboxes" },
    section: "basic",
    keywords: "to-do list to do todo checklist checkbox check box task",
    shortcut: "[]",
  },
  {
    id: "quote",
    icon: { assets: { 16: quotemarkLight16, 20: quotemarkLight20 } },
    label: { id: "codex.space.page.slashMenu.quote", defaultMessage: "Quote", description: "Page editor slash-menu action that inserts a block quote" },
    description: { id: "codex.space.page.slashMenu.quoteDescription", defaultMessage: "Set a quote apart from the text", description: "Supporting text in the Page editor slash menu for inserting a block quote" },
    section: "basic",
    keywords: "quote blockquote",
    shortcut: ">",
  },
  {
    id: "code",
    icon: { assets: { 16: codeLight16, 20: codeLight20 } },
    label: { id: "codex.space.page.slashMenu.code", defaultMessage: "Code", description: "Page editor slash-menu action that inserts a code block" },
    description: { id: "codex.space.page.slashMenu.codeDescription", defaultMessage: "Code with syntax highlighting", description: "Supporting text in the Page editor slash menu for inserting a code block" },
    section: "basic",
    keywords: "code block snippet",
    shortcut: "```",
  },
  {
    id: "table",
    icon: { assets: { 16: tableLight16, 20: tableLight20 } },
    label: { id: "codex.space.page.slashMenu.table", defaultMessage: "Table", description: "Page editor slash-menu action that inserts an editable table" },
    description: { id: "codex.space.page.slashMenu.tableDescription", defaultMessage: "Organize content in rows and columns", description: "Supporting text in the Page editor slash menu for inserting an editable table" },
    section: "basic",
    keywords: "table grid spreadsheet",
  },
  {
    id: "divider",
    icon: { assets: { 16: minusMdLight16, 20: minusMdLight20 } },
    label: { id: "codex.space.page.slashMenu.divider", defaultMessage: "Divider", description: "Page editor slash-menu action that inserts a horizontal divider" },
    description: { id: "codex.space.page.slashMenu.dividerDescription", defaultMessage: "Separate sections with a line", description: "Supporting text in the Page editor slash menu for inserting a horizontal divider" },
    section: "basic",
    keywords: "divider hr horizontal rule",
    shortcut: "---",
  },
  {
    id: "linkPage",
    icon: { assets: { 16: linkLight16, 20: linkLight20 } },
    label: { id: "codex.space.page.slashMenu.linkPage", defaultMessage: "Link to page", description: "Page editor slash-menu action that opens the picker to link to an existing Page" },
    description: { id: "codex.space.page.slashMenu.linkPageDescription", defaultMessage: "Link to an existing page", description: "Supporting text in the Page editor slash menu for opening the picker to link to an existing Page" },
    section: "basic",
    keywords: "link to page existing page",
  },
  {
    id: "prompt",
    icon: { assets: { 16: chatBubbleLight16, 20: chatBubbleLight20 } },
    label: { id: "codex.space.page.slashMenu.prompt", defaultMessage: "Prompt", description: "Page slash command that inserts text readers can click to start a new chat about the Page" },
    description: { id: "codex.space.page.slashMenu.promptDescription", defaultMessage: "A prompt readers can run", description: "Supporting text in the Page editor slash menu for inserting a prompt that readers can click to start a new chat about the Page" },
    section: "basic",
    keywords: "prompt chat conversation",
  },
  {
    id: "callout",
    icon: { assets: { 16: squareTextFormatLight16, 20: squareTextFormatLight20 } },
    label: { id: "codex.space.page.slashMenu.highlight", defaultMessage: "Highlight", description: "Page editor block-menu action that inserts a shaded callout containing editable text and an optional emoji" },
    description: { id: "codex.space.page.slashMenu.calloutDescription", defaultMessage: "Draw attention to a note", description: "Supporting text in the Page editor slash menu for inserting a shaded highlight block with editable text and an optional emoji" },
    section: "basic",
    keywords: "highlight callout note",
  },
  {
    id: "generate",
    icon: { assets: { 16: magicWandLight16, 20: magicWandLight20 } },
    label: { id: "codex.space.page.slashMenu.generate", defaultMessage: "Generate", description: "Page slash command that turns the current paragraph into an inline prompt for generating text" },
    description: { id: "codex.space.page.slashMenu.generateDescription", defaultMessage: "Describe what you want to write", description: "Supporting text in the Page editor slash menu for opening an inline prompt to generate text" },
    section: "generate",
    keywords: "generate agi write draft",
  },
  {
    id: "visualize",
    icon: { assets: { 16: shapesLight16, 20: shapesLight20 } },
    label: { id: "codex.space.page.slashMenu.visualize", defaultMessage: "Visualize", description: "Page editor slash-menu action that opens a prompt for Codex to create an interactive visualization at the cursor" },
    description: { id: "codex.space.page.slashMenu.visualizeDescription", defaultMessage: "Create an interactive visualization", description: "Supporting text in the Page editor slash menu for opening a prompt to create an interactive visualization at the cursor" },
    section: "generate",
    keywords: "visualize visualization interactive",
    commands: ["visualize"],
  },
  {
    id: "visualizeApp",
    icon: { assets: { 16: shapesLight16, 20: shapesLight20 } },
    label: { id: "codex.space.page.slashMenu.visualizeApp", defaultMessage: "Visualize (Create an app)", description: "Slash-menu option that opens Visualize with an editable app creation prompt" },
    description: { id: "codex.space.page.slashMenu.visualizeAppDescription", defaultMessage: "Build an interactive app", description: "Supporting text in the Page editor slash menu for opening an editable prompt to generate an interactive app" },
    section: "generate",
    keywords: "app create an app",
    commands: ["app"],
    prompt: {"id":"codex.space.page.visualization.generation.appStarter","defaultMessage":"Create an app","description":"Editable visualization prompt starter; the user continues typing after these words"},
  },
  {
    id: "visualizeMockup",
    icon: { assets: { 16: shapesLight16, 20: shapesLight20 } },
    label: { id: "codex.space.page.slashMenu.visualizeMockup", defaultMessage: "Visualize (Mock up a screen)", description: "Slash-menu option that opens Visualize with an editable screen mockup prompt" },
    description: { id: "codex.space.page.slashMenu.visualizeMockupDescription", defaultMessage: "Explore a screen design", description: "Supporting text in the Page editor slash menu for opening an editable prompt to generate a screen mockup" },
    section: "generate",
    keywords: "mock mockup mock up a screen",
    commands: ["mock","mockup"],
    prompt: {"id":"codex.space.page.visualization.generation.mockupStarter","defaultMessage":"Mock up a screen","description":"Editable visualization prompt starter for a UI mockup; the user continues typing after these words"},
  },
  {
    id: "visualizeWidget",
    icon: { assets: { 16: shapesLight16, 20: shapesLight20 } },
    label: { id: "codex.space.page.slashMenu.visualizeWidget", defaultMessage: "Visualize (Build a widget)", description: "Slash-menu option that opens Visualize with an editable widget creation prompt" },
    description: { id: "codex.space.page.slashMenu.visualizeWidgetDescription", defaultMessage: "Build a compact interactive tool", description: "Supporting text in the Page editor slash menu for opening an editable prompt to generate a widget" },
    section: "generate",
    keywords: "widget build a widget",
    commands: ["widget"],
    prompt: {"id":"codex.space.page.visualization.generation.widgetStarter","defaultMessage":"Build a widget","description":"Editable visualization prompt starter; the user continues typing after these words"},
  },
  {
    id: "visualizeDiagram",
    icon: { assets: { 16: shapesLight16, 20: shapesLight20 } },
    label: { id: "codex.space.page.slashMenu.visualizeDiagram", defaultMessage: "Visualize (Draw a diagram)", description: "Slash-menu option that opens Visualize with an editable diagram creation prompt" },
    description: { id: "codex.space.page.slashMenu.visualizeDiagramDescription", defaultMessage: "Explain an idea with a diagram", description: "Supporting text in the Page editor slash menu for opening an editable prompt to generate a diagram" },
    section: "generate",
    keywords: "diagram draw a diagram",
    commands: ["diagram"],
    prompt: {"id":"codex.space.page.visualization.generation.diagramStarter","defaultMessage":"Draw a diagram","description":"Editable visualization prompt starter; the user continues typing after these words"},
  },
  {
    id: "image",
    icon: { assets: { 16: photoLight16, 20: photoLight20 } },
    label: { id: "codex.space.page.slashMenu.image", defaultMessage: "Image", description: "Page editor slash-menu action that inserts an image block for uploading or generating an image" },
    description: { id: "codex.space.page.slashMenu.imageDescription", defaultMessage: "Upload or generate an image", description: "Supporting text in the Page editor slash menu for inserting an image block for uploading or generating an image" },
    section: "media",
    keywords: "image photo picture upload generate",
  },
  {
    id: "file",
    icon: { assets: { 16: paperclipLight16, 20: paperclipLight20 } },
    label: { id: "codex.space.page.slashMenu.file", defaultMessage: "File", description: "Page editor slash-menu action that opens a file picker to upload attachments" },
    description: { id: "codex.space.page.slashMenu.fileDescription", defaultMessage: "Upload a file for download", description: "Supporting text in the Page editor slash menu for opening the file picker to upload an attachment" },
    section: "media",
    keywords: "file attachment upload",
  },
  {
    id: "mentionFiles",
    icon: { assets: { 16: atSignLight16, 20: atSignLight20 } },
    label: { id: "codex.space.page.slashMenu.mentionFiles", defaultMessage: "Files", description: "Page editor slash-menu action that opens file mentions" },
    description: { id: "codex.space.page.slashMenu.mentionFilesDescription", defaultMessage: "Reference a file in this page", description: "Supporting text in the Page editor slash menu for opening the file mention picker" },
    section: "mentioned",
    keywords: "mention files reference",
  },
  {
    id: "mentionPages",
    icon: { assets: { 16: textPageLight16, 20: textPageLight20 } },
    label: { id: "codex.space.page.slashMenu.mentionPages", defaultMessage: "Pages", description: "Page editor slash-menu action that opens Page mentions" },
    description: { id: "codex.space.page.slashMenu.mentionPagesDescription", defaultMessage: "Reference a page", description: "Supporting text in the Page editor slash menu for opening the Page mention picker" },
    section: "mentioned",
    keywords: "mention pages reference",
  },
  {
    id: "mentionChats",
    icon: { assets: { 16: chatBubbleOnChatBubbleLight16, 20: chatBubbleOnChatBubbleLight20 } },
    label: { id: "codex.space.page.slashMenu.mentionChats", defaultMessage: "Chats", description: "Page editor slash-menu action that opens chat mentions" },
    description: { id: "codex.space.page.slashMenu.mentionChatsDescription", defaultMessage: "Reference a chat", description: "Supporting text in the Page editor slash menu for opening the chat mention picker" },
    section: "mentioned",
    keywords: "mention chats conversations tasks",
  },
  {
    id: "columnLeft",
    icon: { assets: { 16: tableColumnLight16, 20: tableColumnLight20 } },
    label: { id: "codex.space.page.slashMenu.columnLeft", defaultMessage: "Add column left", description: "Page editor slash-menu action that inserts a table column to the left" },
    description: { id: "codex.space.page.slashMenu.columnLeftDescription", defaultMessage: "Insert a column before this one", description: "Supporting text in the Page editor slash menu for inserting a table column to the left of the selected column" },
    section: "table",
    keywords: "column left add column left insert column left",
  },
  {
    id: "columnRight",
    icon: { assets: { 16: tableColumnLight16, 20: tableColumnLight20 } },
    label: { id: "codex.space.page.slashMenu.columnRight", defaultMessage: "Add column right", description: "Page editor slash-menu action that inserts a table column to the right" },
    description: { id: "codex.space.page.slashMenu.columnRightDescription", defaultMessage: "Insert a column after this one", description: "Supporting text in the Page editor slash menu for inserting a table column to the right of the selected column" },
    section: "table",
    keywords: "column right add column right insert column right",
  },
  {
    id: "columnDelete",
    icon: { assets: { 16: trashLight16, 20: trashLight20 } },
    label: { id: "codex.space.page.slashMenu.columnDelete", defaultMessage: "Delete column", description: "Page editor slash-menu action that deletes the selected table column" },
    description: { id: "codex.space.page.slashMenu.columnDeleteDescription", defaultMessage: "Remove this column and its contents", description: "Supporting text in the Page editor slash menu for deleting the selected table column" },
    section: "table",
    keywords: "column delete remove column delete column",
  },
  {
    id: "generatePrompt",
    icon: { assets: { 16: magicWandLight16, 20: magicWandLight20 } },
    label: { id: "codex.space.page.slashMenu.generatePrompt", defaultMessage: "Generate", description: "Slash-menu action that immediately submits the text after the slash as a generation request" },
    description: { id: "codex.space.page.slashMenu.generatePromptDescription", defaultMessage: "Turn your prompt into text", description: "Supporting text in the Page editor slash menu for immediately submitting the typed slash query as a text generation request" },
    section: "generatePrompt",
    keywords: "",
  },
];
