
import React, { useState, useCallback, useEffect } from 'react';
import { useSearchParams, useNavigate, useLocation } from 'react-router-dom';
import { GoogleGenerativeAI } from '@google/generative-ai';
import Sidebar from './workbench/WorkbenchSidebar';
import MainPreview from './workbench/WorkbenchPreview';
import logoG from '@willow/assets/brand/logo-glyph.png';
import { useAutoSave } from './use-auto-save';
import { useAuth } from '@willow/auth/AuthContext';
import { useUserDataContext } from '@willow/auth/UserDataContext';
import { useLocalFS } from '@willow/storage/local-fs/LocalFSContext';
import { testStore } from '@willow/ai/computer-use/test-store';
import { MessageLoading } from '@willow/ui/message-loading';
import { PROJECT_NAME_MODEL } from '@models';
import { PROJECTS_UPDATED_EVENT, readProjectRegistry, writeProjectRegistry } from '@willow/projects/registry';

interface WorkbenchViewProps {
  prompt?: string;
  onSettingsClick?: (tab?: string) => void;
  modelConfig: any;
  setModelConfig: React.Dispatch<React.SetStateAction<any>>;
  selectedModelId: string;
  setSelectedModelId: (id: string) => void;
}

const WorkbenchView: React.FC<WorkbenchViewProps> = ({ prompt: propPrompt, onSettingsClick, modelConfig, setModelConfig, selectedModelId, setSelectedModelId }) => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const location = useLocation();
  const urlPrompt = searchParams.get('prompt') || '';
  const projectId = searchParams.get('projectId') || '';
  const urlMode = searchParams.get('mode') || 'ship';
  const prompt = propPrompt || urlPrompt;
  const initialAttachments = location.state?.initialAttachments;

  // Auth context for Drive integration
  const { user, accessToken } = useAuth();

  // API keys for AI generation
  const { apiKeys } = useUserDataContext();

  // Project name - generated by AI from prompt
  const [projectName, setProjectName] = useState('');
  const [projectHydrated, setProjectHydrated] = useState(!projectId);
  const [isGeneratingName, setIsGeneratingName] = useState(false);
  const nameGeneratedRef = React.useRef(false);
  // Capture whether THIS mount is a genuinely new project at first render. A new
  // project arrives with location.state.isNewProject === true; on a later return
  // the sidebar has flipped it to false. Captured in a ref so a concurrent flip
  // can't change it mid-effect.
  const isNewProjectRef = React.useRef(location.state?.isNewProject === true);
  const handleProjectHydrated = useCallback(() => {
    // The sidebar also mounts once before an existing project's scoped name is
    // resolved. Do not let that empty/default pass unlock autosave.
    if (!projectId || projectName) setProjectHydrated(true);
  }, [projectId, projectName]);

  // Existing projects reopen by durable id. Resolving the display/folder name
  // from the scoped registry lets WorkbenchSidebar load the saved chat session and
  // its file snapshot instead of starting from the template.
  useEffect(() => {
    if (!projectId) return;
    setProjectHydrated(false);
    const resolveExistingProject = () => {
      const existing = (readProjectRegistry() as any[]).find((project: any) => project?.id === projectId);
      if (existing?.name) {
        setProjectName(existing.name);
        nameGeneratedRef.current = true;
        isNewProjectRef.current = false;
      }
    };
    resolveExistingProject();
    window.addEventListener(PROJECTS_UPDATED_EVENT, resolveExistingProject);
    return () => window.removeEventListener(PROJECTS_UPDATED_EVENT, resolveExistingProject);
  }, [projectId]);

  // Register a brand-new code project in the localStorage registry, returning the
  // name actually used. For a genuinely new project a colliding name is
  // disambiguated ("Name (2)") instead of being dropped — dropping was why new
  // projects with a duplicate generated name silently never appeared. On a return
  // to an existing project we reuse its entry by name so we never create dupes.
  const registerCodeProject = useCallback((desiredName: string): string => {
    try {
      let list = readProjectRegistry() as any[];
      if (!Array.isArray(list)) list = [];
      const existing = list.find((p: any) => p?.name?.toLowerCase() === desiredName.toLowerCase());
      if (existing) {
        if (!isNewProjectRef.current) {
          // Return to an existing project — reuse it, don't duplicate.
          return existing.name;
        }
        // Different new project that happens to share a name — disambiguate.
        let counter = 2;
        let candidate = `${desiredName} (${counter})`;
        while (list.some((p: any) => p?.name?.toLowerCase() === candidate.toLowerCase())) {
          counter++;
          candidate = `${desiredName} (${counter})`;
        }
        desiredName = candidate;
      }
      // Mint an id no existing project already uses — the 4-digit space is
      // small enough for birthday collisions, and a duplicate id cross-links
      // two projects' covers/media in IndexedDB.
      const usedIds = new Set(list.map((p: any) => p?.id).filter(Boolean));
      let newId = `#${Math.floor(1000 + Math.random() * 9000)}`;
      while (usedIds.has(newId)) {
        newId = `#${Math.floor(1000 + Math.random() * 9000)}`;
      }
      list.push({ id: newId, name: desiredName, kind: 'code' });
      writeProjectRegistry(list);
      window.dispatchEvent(new Event('willow_projects_updated'));
      return desiredName;
    } catch {
      return desiredName;
    }
  }, []);

  // Generate project name from prompt using AI
  useEffect(() => {
    if (projectId || !prompt || nameGeneratedRef.current) return;
    // Need at least one provider key to attempt naming AND to register the
    // project. Previously this required a GEMINI key specifically, so a user whose
    // naming provider is Claude/OpenAI (no gemini key) never got their project
    // registered in willow_projects_list — it silently never appeared. Proceed if
    // ANY provider key is present; the provider is chosen below, and if naming
    // fails we still register a fallback name so the project always shows up.
    if (!apiKeys.gemini?.[0] && !apiKeys.openai?.[0] && !apiKeys.anthropic?.[0] && !apiKeys.moonshot?.[0] && !apiKeys.spacexai?.[0] && !apiKeys.zhipuai?.[0]) return;

    const generateProjectName = async () => {
      nameGeneratedRef.current = true;
      setIsGeneratingName(true);

      try {
        const chatNamingSelectionId = modelConfig?.systemDefaults?.chatRenaming || 'gemini-3.1-flash-lite';
        
        const allModels = [
          ...(modelConfig?.gemini?.savedModels || []).map((m: any) => ({ ...m, provider: 'gemini' as const })),
        ...(modelConfig?.openai?.savedModels || []).map((m: any) => ({ ...m, provider: 'openai' as const })),
        ...(modelConfig?.anthropic?.savedModels || []).map((m: any) => ({ ...m, provider: 'anthropic' as const })),
        ...(modelConfig?.moonshot?.savedModels || []).map((m: any) => ({ ...m, provider: 'moonshot' as const })),
        ...(modelConfig?.spacexai?.savedModels || []).map((m: any) => ({ ...m, provider: 'spacexai' as const })),
        ...(modelConfig?.zhipuai?.savedModels || []).map((m: any) => ({ ...m, provider: 'zhipuai' as const })),
        ...(modelConfig?.moonshot?.savedModels || []).map((m: any) => ({ ...m, provider: 'moonshot' as const })),
        ...(modelConfig?.spacexai?.savedModels || []).map((m: any) => ({ ...m, provider: 'spacexai' as const })),
        ...(modelConfig?.zhipuai?.savedModels || []).map((m: any) => ({ ...m, provider: 'zhipuai' as const })),
        ...(modelConfig?.moonshot?.savedModels || []).map((m: any) => ({ ...m, provider: 'moonshot' as const })),
        ...(modelConfig?.spacexai?.savedModels || []).map((m: any) => ({ ...m, provider: 'spacexai' as const })),
        ...(modelConfig?.zhipuai?.savedModels || []).map((m: any) => ({ ...m, provider: 'zhipuai' as const })),
        ];
        
        let targetProvider = 'gemini';
        let targetModelId = 'gemini-3.1-flash-lite';
        
        if (chatNamingSelectionId === 'gemini-3.1-flash-lite') {
          targetProvider = 'gemini';
          targetModelId = 'gemini-3.1-flash-lite';
        } else if (chatNamingSelectionId === 'claude-sonnet-4.5') {
            targetProvider = 'anthropic';
            targetModelId = 'claude-sonnet-4.5';
        } else {
            const sel = allModels.find((m) => m.modelId === chatNamingSelectionId);
            if (sel) {
              targetProvider = sel.provider;
              targetModelId = sel.modelId;
            }
        }
        
        const apiKey = apiKeys?.[targetProvider]?.[0];
        if (!apiKey) throw new Error('No API key for configured project naming provider');

        const promptText = `Generate a creative project name for an app. Use 2-3 words (preferred) or 1 word if catchy. Focus on WHAT the app does, not HOW it's being built. Ignore words like "code", "build", "create", "make" in the request - just name the app itself. Return ONLY the name, no quotes.\n\nApp description: ${prompt}`;
        let name = '';

        if (targetProvider === 'gemini') {
            const response = await fetch(
              `https://generativelanguage.googleapis.com/v1beta/models/${targetModelId}:generateContent?key=${apiKey}`,
              {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  contents: [{ parts: [{ text: promptText }] }]
                })
              }
            );
            if (response.ok) {
              const data = await response.json();
              name = data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || '';
            }
        } else if (targetProvider === 'openai') {
            const response = await fetch('https://api.openai.com/v1/chat/completions', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${apiKey}`
              },
              body: JSON.stringify({
                model: targetModelId,
                messages: [{ role: 'user', content: promptText }]
              })
            });
            if (response.ok) {
                const data = await response.json();
                name = data?.choices?.[0]?.message?.content?.trim() || '';
            }
        } else if (targetProvider === 'anthropic') {
            const response = await fetch('https://api.anthropic.com/v1/messages', {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                  'x-api-key': apiKey,
                  'anthropic-version': '2023-06-01',
                  'anthropic-cors-bypass': 'true'
                },
                body: JSON.stringify({
                  model: targetModelId,
                  max_tokens: 50,
                  messages: [{ role: 'user', content: promptText }]
                })
              });
              if (response.ok) {
                  const data = await response.json();
                  name = data?.content?.[0]?.text?.trim() || '';
              }
        }

        if (!name) name = 'New Project';
        // Clean up: remove quotes if present, strip filesystem-illegal
        // characters (the name becomes the Code/<name> folder on disk — ':'
        // etc. make every folder operation throw "Name is not allowed" on
        // Windows and the project silently never syncs), limit length.
        const cleanName = (name.replace(/^["']|["']$/g, '').replace(/[\/:*?"<>|]/g, '').substring(0, 30) || 'New Project').trim() || 'New Project';

        // Register in willow_projects_list (disambiguates instead of dropping).
        const registeredName = registerCodeProject(cleanName);

        setProjectName(registeredName);
      } catch (error) {
        const fallbackName = 'New Project';
        const registeredName = registerCodeProject(fallbackName);
        setProjectName(registeredName);
      } finally {
        setIsGeneratingName(false);
      }
    };

    generateProjectName();
  }, [projectId, prompt, apiKeys.gemini, apiKeys.openai, apiKeys.anthropic]);

  // Auto-save when logged in (Google Drive) or when local folder is connected
  const { isLocalFolderConnected } = useLocalFS();
  // Gate autosave on a resolved projectName so an early save can't create a
  // phantom "Untitled" folder/project before the AI name (or fallback) is set.
  const { isSaving, saveNow } = useAutoSave(
    projectName || 'Untitled',
    (!!accessToken || isLocalFolderConnected) && !!projectName && projectHydrated,
  );

  // Initialize chat mode if URL mode is 'chat'
  const [isChatMode, setIsChatMode] = useState(urlMode === 'chat');

  // If user enters via chat mode, we start centered. 
  // We can manage layout state: 'centered' vs 'sidebar'
  // When isChatMode is true: Sidebar is centered, width is constrained but visually centered, Preview is hidden (or off-screen).
  // When isChatMode is false: Standard resizing logic applies.

  const [sidebarWidth, setSidebarWidth] = useState(400);
  const [lastSidebarWidth, setLastSidebarWidth] = useState(400);
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const [isTransitioning, setIsTransitioning] = useState(false);
  const transitionTimerRef = React.useRef<ReturnType<typeof setTimeout> | null>(null);

  // Cleanup transition timers on unmount
  React.useEffect(() => {
    return () => {
      if (transitionTimerRef.current) clearTimeout(transitionTimerRef.current);
    };
  }, []);

  const setTransitionTimeout = useCallback(() => {
    if (transitionTimerRef.current) clearTimeout(transitionTimerRef.current);
    transitionTimerRef.current = setTimeout(() => setIsTransitioning(false), 500);
  }, []);

  const toggleSidebar = useCallback(() => {
    // Set transitioning flag to disable iframe interactions during animation
    setIsTransitioning(true);
    setIsSidebarCollapsed(prev => {
      if (!prev) {
        setLastSidebarWidth(sidebarWidth);
      }
      return !prev;
    });
    // Clear transitioning after animation duration (500ms)
    setTransitionTimeout();
  }, [sidebarWidth, setTransitionTimeout]);

  const startResizing = useCallback(() => {
    setIsDragging(true);
  }, []);

  const stopResizing = useCallback(() => {
    setIsDragging(false);
  }, []);

  // Use refs to avoid stale closure issues in resize callback
  const isDraggingRef = React.useRef(isDragging);
  const isSidebarCollapsedRef = React.useRef(isSidebarCollapsed);
  
  // Keep refs in sync with state
  React.useEffect(() => {
    isDraggingRef.current = isDragging;
  }, [isDragging]);
  
  React.useEffect(() => {
    isSidebarCollapsedRef.current = isSidebarCollapsed;
  }, [isSidebarCollapsed]);

  // Use ref to store pending width for RAF throttling
  const pendingWidthRef = React.useRef<number | null>(null);
  const rafRef = React.useRef<number | null>(null);

  const resize = useCallback(
    (mouseMoveEvent: MouseEvent) => {
      // Use refs to get current values
      if (isDraggingRef.current) {
        const newWidth = mouseMoveEvent.clientX;
        const totalWidth = document.body.clientWidth;
        
        // Constraints
        const minWidth = totalWidth / 5;
        const maxWidth = totalWidth * 0.37;
        const collapseThreshold = minWidth * 0.5;

        if (isSidebarCollapsedRef.current) {
          if (newWidth > collapseThreshold) {
            setIsTransitioning(true);
            setIsSidebarCollapsed(false);
            setSidebarWidth(minWidth);
            setIsDragging(false);
            if (transitionTimerRef.current) clearTimeout(transitionTimerRef.current);
            transitionTimerRef.current = setTimeout(() => setIsTransitioning(false), 500);
          }
        } else {
          if (newWidth < collapseThreshold) {
            setIsTransitioning(true);
            setIsSidebarCollapsed(true);
            setIsDragging(false);
            if (transitionTimerRef.current) clearTimeout(transitionTimerRef.current);
            transitionTimerRef.current = setTimeout(() => setIsTransitioning(false), 500);
            return;
          }

          // Calculate target width
          let targetWidth = newWidth;
          if (newWidth < minWidth && newWidth >= collapseThreshold) {
            targetWidth = minWidth;
          } else if (newWidth > maxWidth) {
            targetWidth = maxWidth;
          } else if (newWidth < minWidth) {
            return;
          }

          // Use requestAnimationFrame for smooth updates
          pendingWidthRef.current = targetWidth;
          if (!rafRef.current) {
            rafRef.current = requestAnimationFrame(() => {
              if (pendingWidthRef.current !== null) {
                setSidebarWidth(pendingWidthRef.current);
              }
              rafRef.current = null;
            });
          }
        }
      }
    },
    [] // No dependencies - uses refs for current values
  );

  useEffect(() => {
    window.addEventListener("mousemove", resize);
    window.addEventListener("mouseup", stopResizing);
    return () => {
      window.removeEventListener("mousemove", resize);
      window.removeEventListener("mouseup", stopResizing);
      if (rafRef.current) {
        cancelAnimationFrame(rafRef.current);
      }
    };
  }, [resize, stopResizing]);

  const [activeTab, setActiveTab] = useState('preview');
  
  // Note: Test mode is no longer tied to activeTab
  // testStore.enterTestMode() is called when test starts in WorkbenchSidebar.startTestGeneration()
  // testStore.exitTestMode() is called when test completes
  
  // Calculate effective layout based on chat mode
  const containerStyle = isChatMode 
    ? { width: '100%' } 
    : { width: `${isSidebarCollapsed ? 0 : sidebarWidth}px` };

  const minimizeChat = useCallback(() => {
    setIsChatMode(false);
  }, []);

  return (
    <div className={`flex h-full w-full bg-[#1c1c1c] overflow-hidden text-sm relative ${isDragging ? 'cursor-[ew-resize] select-none' : ''}`}>
      
      {/* Header - Rendered at root level in Chat Mode for true left-edge positioning */}
      {isChatMode && (
        <div className="absolute top-0 left-0 right-0 h-14 flex items-center justify-between z-30 bg-[#1c1c1c]">
          <div className="flex items-center min-w-0 h-full" style={{ paddingLeft: '21px' }}>
            {/* Logo Button — Squircle hover background, studio home link */}
            <button 
              onClick={() => navigate('/')}
              className="flex items-center justify-center p-1.5 hover:bg-white/5 transition-colors rounded-xl flex-shrink-0"
              title="Back to Dashboard"
            >
              <img src={logoG} alt="Logo" className="h-[24px] w-auto flex-shrink-0" />
            </button>
            
            <div className="flex-shrink-0 w-[1px]" />
            
            {/* Project Title and Toggle - Separate squircle hover */}
            <div
              className="flex items-center gap-2 cursor-pointer hover:bg-white/5 px-2 py-1.5 rounded-xl transition-colors min-w-0"
              title="Project Settings"
            >
              {isGeneratingName ? (
                <MessageLoading className="scale-75" />
              ) : (
                <span className="font-semibold text-gray-200 truncate">{projectName || 'New Project'}</span>
              )}
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-500">
                <path d="m6 9 6 6 6-6"/>
              </svg>
            </div>
          </div>
          
          {/* Exit Fullscreen Button */}
          <div className="flex items-center px-[27px]">
            <button 
              onClick={minimizeChat}
              className="p-1.5 rounded-lg bg-transparent text-gray-500 hover:text-white transition-colors hover:bg-white/5"
              title="Exit Fullscreen"
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M8 3v3a2 2 0 0 1-2 2H3m18 0h-3a2 2 0 0 1-2-2V3m0 18v-3a2 2 0 0 1 2-2h3M3 16h3a2 2 0 0 1 2 2v3"/>
              </svg>
            </button>
          </div>
        </div>
      )}

      <div 
        style={{
          ...containerStyle,
          willChange: isDragging ? 'width' : 'auto',
          ...(!isDragging && {
            transitionProperty: 'width',
            transitionDuration: '500ms',
            transitionTimingFunction: 'cubic-bezier(0.32, 0.72, 0, 1)'
          })
        }} 
        className={`flex-shrink-0 overflow-hidden relative z-10
          bg-[#1c1c1c]`}
      >
        <div
          className="h-full"
          style={{ 
            position: 'relative',
            left: isChatMode ? '50%' : '0',
            transform: isChatMode ? 'translateX(-50%)' : 'translateX(0)',
            width: isChatMode ? '800px' : '100%',
            ...(!isDragging && {
              transitionProperty: isChatMode ? 'left, transform, width' : 'width',
              transitionDuration: '500ms',
              transitionTimingFunction: 'cubic-bezier(0.32, 0.72, 0, 1)'
            })
          }}
        >
          <Sidebar
            width={isChatMode ? 800 : sidebarWidth}
            isCollapsed={isSidebarCollapsed}
            onToggle={toggleSidebar}
            prompt={prompt}
            initialAttachments={initialAttachments}
            activeTab={activeTab}
            onTabChange={setActiveTab}
            isChatMode={isChatMode}
            modelConfig={modelConfig}
            setModelConfig={setModelConfig}
            selectedModelId={selectedModelId}
            setSelectedModelId={setSelectedModelId}
            isResizing={isDragging}
            projectName={projectName}
            isGeneratingName={isGeneratingName}
            onSettingsClick={onSettingsClick}
            onProjectHydrated={handleProjectHydrated}
          />
        </div>
      </div>
      
      {/* Resizer Handle - Always rendered but hidden in Chat Mode */}
      <div 
        className={`w-0 relative z-50 group flex-shrink-0 transition-opacity duration-300 ${isChatMode ? 'opacity-0 pointer-events-none' : 'opacity-100'}`}
        onMouseDown={startResizing}
      >
          <div
            className={`absolute w-[2px] left-0 rounded-full ${isDragging ? '' : 'transition-opacity duration-300 ease-in-out'}
              bg-gradient-to-b from-transparent via-[#3b82f6] to-transparent
              ${isDragging ? 'opacity-100' : 'opacity-0 group-hover:opacity-100'}
            `}
             style={{ 
               top: '56px', 
               bottom: '16px', 
               transform: isSidebarCollapsed ? 'translate3d(15px, 0, 0)' : 'translate3d(-1px, 0, 0)',
               willChange: 'transform',
               maskImage: 'linear-gradient(to bottom, transparent, black 128px, black calc(100% - 128px), transparent)',
               WebkitMaskImage: 'linear-gradient(to bottom, transparent, black 128px, black calc(100% - 128px), transparent)'
             }}
          />
         
         <div 
            className={`absolute top-14 bottom-4 -left-1 bg-transparent cursor-[ew-resize] hover:bg-transparent ${isSidebarCollapsed ? '-right-4' : '-right-1'}`} 
         />
      </div>

      {/* Main Preview - Slides in from right */}
      <div
        className={`flex-1 min-w-0 ${isChatMode ? 'opacity-0 translate-x-[100px] pointer-events-none' : 'opacity-100 translate-x-0'}`}
        style={{
          ...(!isDragging && {
            transitionProperty: 'opacity, transform',
            transitionDuration: '500ms',
            transitionTimingFunction: 'cubic-bezier(0.32, 0.72, 0, 1)'
          })
        }}
      >
        <MainPreview
            isSidebarCollapsed={isSidebarCollapsed}
            onToggleSidebar={toggleSidebar}
            activeTab={activeTab}
            onTabChange={setActiveTab}
            onSettingsClick={onSettingsClick}
            isResizing={isDragging}
            isTransitioning={isTransitioning}
            selectedModelId={selectedModelId}
            modelConfig={modelConfig}
            projectName={projectName}
        />
      </div>
    </div>
  );
};

export default React.memo(WorkbenchView);
