fn main() {
    // Declaring the app's own commands makes each one a permission that capabilities grant
    // explicitly: the strip and Willow's pages each get only the ones they call.
    let commands = tauri_build::AppManifest::new().commands(&[
        "tabs_snapshot",
        "tab_report",
        "tab_history",
        "window_close",
        "tab_frame",
        "window_buttons",
        "menu_open",
        "menu_key",
        "menu_mnemonics",
        "menu_keys",
        "strip_tooltip",
        "strip_panel_tabs",
        "panel_tab",
        "window_fullscreen",
        "context_menu_choose",
        "app_quit",
        "overlay_open",
        "overlay_close",
        "overlay_post",
        "overlay_surface",
        "overlay_attached",
        "overlay_set_interactive",
        "overlay_set_focusable",
        "overlay_send",
        "pets_read",
        "pets_load",
        "pets_prepare_creation",
        "pets_open_folder",
        "pets_read_image",
        "pets_write_image",
        "pets_report_shown",
        "pets_show",
        "pets_toggle",
        "pages_stream",
        "pages_stream_cancel",
        "harness_connection",
        "harness_exposure",
        "harness_set_exposure",
        "harness_set_tailscale_serve",
        "harness_tailscale",
        "harness_set_badge",
        "harness_preview",
        "local_folder_open",
        "snapshot_configure",
        "snapshot_state",
        "snapshot_check_shortcut",
        "snapshot_suppress",
        "snapshot_pending",
        "snapshot_read",
        "snapshot_ack",
    ]);
    // Tauri's default Windows manifest plus OS compatibility, which layered child windows need.
    let windows = tauri_build::WindowsAttributes::new().app_manifest(include_str!("app.manifest"));
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(commands).windows_attributes(windows))
        .expect("failed to run tauri-build");
}
