// Visual Editor - Barrel Export
export * from './types';
export { visualEditorStore } from './visual-editor-store';
export {
  isVisualEditMode,
  isScanning,
  isSaving,
  inspectorReady,
  hoveredElement,
  selectedElement,
  selectedElements,
  isVisualEditing,
  codeNavigationRequest,
  visualEditQueue,
  undoHistory,
  canUndo,
  previewRefreshRequest,
  parentSelectionRequested,
  isAtRootLevel,
  pendingSelectionRestore,
  enterVisualEdit,
  exitVisualEdit,
  selectElement,
  setSelectedElements,
  clearSelection,
  setHoveredElement,
  handleInspectorMessage,
  navigateToCode,
  addToVisualEditQueue,
  dequeueVisualEdit,
  clearVisualEditQueue,
  pushUndoState,
  undoLastVisualEdit,
  clearUndoHistory,
  selectParentElement,
  requestInspectorReinit,
  immediateInspectorReinit,
  hasUnsavedChanges,
  markAsUnsaved,
  saveVisualChanges,
  discardVisualChanges,
  checkUnsavedStatus,
} from './visual-editor-store';
export { applyVisualEdit, getElementDescription } from './visual-edit-service';
export {
  applyDirectStyle,
  applyDirectStyles,
  deleteElement,
  getCurrentStyles,
  getFreshComputedStyles,
  formatColorForDisplay,
  isTransparent,
  tailwindColorToCss,
  TAILWIND_COLOR_MAP,
  BORDER_RADIUS_MAP,
  SHADOW_MAP,
  OPACITY_MAP,
  FONT_SIZE_MAP,
  FONT_WEIGHT_MAP,
  TEXT_ALIGN_MAP,
  BORDER_WIDTH_MAP,
  BORDER_STYLE_MAP,
  type StyleProperty,
  type DirectStyleResult,
} from './direct-style-service';
