/**
 * The /images page's templates (Gemini's sidebar Images entry), captured Oct 2026 off the live app
 * by tools/ui-research/scrapers/gemini/media-tools-2026/14-images-templates.cjs; regenerate with
 * tools/media/gen-images-page-templates.cjs. Names, art and each dialog's line are Gemini's. The
 * prompt is what "Choose photo" sends as the user's message: Plushie's is Gemini's own, the rest
 * Willow's, because Gemini's client only has them once a template is sent. Gemini reshuffles the
 * set on every visit, so this is a snapshot.
 */
export interface ImagesPageTemplate {
  id: string;
  name: string;
  /** The portrait card art. */
  image: string;
  /** The dialog's landscape art. */
  preview: string;
  /** The dialog's line above "Add a photo to see it transform." */
  line: string;
  prompt: string;
}

export const IMAGES_PAGE_TEMPLATES: ImagesPageTemplate[] = [
  {"id":"images-page-ROW_mural","name":"Mural","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/ROW_mural_thumbnail.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/ROW_mural_modal.webp","line":"Turn into a fan mural.","prompt":"A giant hand-painted fan mural of the person on a city wall. Bold brushwork, drips and stencil shapes, team colours, fans gathered on the pavement below, late afternoon sun."},
  {"id":"images-page-enamel","name":"Pin","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/enamel_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/enamel_l_2x.webp","line":"Turn into a shiny enamel pin.","prompt":"A shiny enamel pin of the person. Bold gold metal outlines, flat glossy enamel colours, a tiny clutch back, pinned to a denim jacket and shot as a close-up product photo."},
  {"id":"images-page-ROW_slide","name":"Slide","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/ROW_slide_thumbnail.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/ROW_slide_modal.webp","line":"Picture yourself in a celebratory slide.","prompt":"The person mid-ride on a giant celebratory slide, arms up, with confetti, streamers and balloons in the air. Bright party light, a joyful candid moment."},
  {"id":"images-page-statue","name":"Marble","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/statue_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/statue_l_2x.webp","line":"Turn into an ancient marble statue.","prompt":"An ancient white marble statue of the person, finely carved with classical drapery and weathered edges, standing in a quiet museum hall under soft skylight."},
  {"id":"images-page-florist","name":"Bloom","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/florist_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/florist_l_2x.webp","line":"Picture yourself with a bouquet of exotic blooms.","prompt":"The person holding an enormous bouquet of exotic blooms: protea, orchids, birds of paradise and trailing greenery. Soft natural light, a lush editorial portrait."},
  {"id":"images-page-origami","name":"Origami","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/origami_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/origami_l_2x.webp","line":"Turn into an origami sculpture.","prompt":"An origami sculpture of the person folded from crisp coloured paper, every crease and facet visible, standing on a plain studio backdrop under soft light."},
  {"id":"images-page-90sstyle","name":"NYC","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/90sstyle_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/90sstyle_l_2x.webp","line":"Imagine yourself in 1990s NYC.","prompt":"The person on a 1990s New York street in full ’90s fashion: baggy denim, a puffer jacket, yellow cabs and a deli sign behind. Grainy film, direct flash."},
  {"id":"images-page-frontrow","name":"Front row","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/frontrow_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/frontrow_l_2x.webp","line":"Picture yourself front row at a fashion show.","prompt":"The person seated front row at a fashion show in a striking outfit, models walking the runway, photographers’ flashes going off, a glamorous crowd."},
  {"id":"images-page-arcade","name":"Arcade","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/arcade_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/arcade_l_2x.webp","line":"Picture yourself in a retro arcade.","prompt":"The person in a retro arcade, lit by glowing cabinet screens and neon signs, mid-game at a classic machine, a candid shot on warm film."},
  {"id":"images-page-chibikeychain","name":"Chibi","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/chibikeychain_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/chibikeychain_l_2x.webp","line":"Turn into a chibi keychain.","prompt":"A cute chibi keychain charm of the person: big head, tiny body, glossy acrylic with a bright outline, hanging from a metal keyring over a soft pastel background."},
  {"id":"images-page-ROW_coach","name":"Coach","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/ROW_coach_thumbnail.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/ROW_coach_modal.webp","line":"Picture yourself as the team’s head coach.","prompt":"The person as the team’s head coach on the sideline: team jacket, clipboard and whistle, players and stadium lights behind, a game-day moment."},
  {"id":"images-page-bench","name":"Dappled","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/bench_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/bench_l_2x.webp","line":"Picture yourself in dappled city light.","prompt":"The person on a city bench in dappled light, patterns of sun and leaf shadow falling across them, warm golden hour, a quiet street portrait."},
  {"id":"images-page-diner","name":"Mug","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/diner_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/diner_l_2x.webp","line":"Turn into a character on a classic diner mug.","prompt":"The person as a cartoon character printed on a classic white diner mug, bold retro linework and a speech bubble, the mug steaming on a diner counter."},
  {"id":"images-page-plushie","name":"Plushie","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/plushie_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/plushie_l_2x.webp","line":"Turn into a squishy, giant plushie.","prompt":"Ultra-soft, round, marshmallow-like giant squishy plushie. Pastel fleece version of full outfit, accessories, and hairstyle. Simple embroidered dot eyes and a tiny stitched smile. Plushie rests playfully on a messy, cozy unmade bed surrounded by warm fairy lights."},
  {"id":"images-page-elven","name":"Elven","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/elven_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/elven_l_2x.webp","line":"Imagine yourself in an elven world.","prompt":"The person as an elf in an ancient forest city: delicate elven attire, pointed ears, silver jewellery, towering trees and soft ethereal light."},
  {"id":"images-page-hollywood","name":"Hollywood","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/hollywood_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/hollywood_l_2x.webp","line":"Imagine yourself as a 1940s Hollywood star.","prompt":"The person as a 1940s Hollywood star: a glamorous black-and-white studio portrait with sculpted hair, a satin gown or tailored suit, and dramatic key light."},
  {"id":"images-page-skydiver","name":"Jump","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/skydiver_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/skydiver_l_2x.webp","line":"Picture yourself mid-jump as a pro skydiver.","prompt":"The person mid-jump as a pro skydiver in free fall high above the clouds: a bright jumpsuit, goggles, arms spread, the horizon curving below."},
  {"id":"images-page-headshot","name":"Headshot","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/headshot_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/headshot_l_2x.webp","line":"Turn your photo into a professional headshot.","prompt":"A professional headshot of the person: business attire, a clean neutral backdrop, soft studio lighting, sharp focus and a confident expression."},
  {"id":"images-page-popup","name":"Pop up","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/popup_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/popup_l_2x.webp","line":"Turn into the page of an antique pop-up book.","prompt":"The person as a paper figure rising from the page of an antique pop-up book, aged paper, folded scenery and hand-lettered captions around them."},
  {"id":"images-page-rainycity","name":"Neon","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/rainycity_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/rainycity_l_2x.webp","line":"Picture yourself in a neon city glow.","prompt":"The person in a city at night glowing with neon, pink and cyan signs reflected on wet streets, light rain, a cinematic portrait."},
  {"id":"images-page-clawgame","name":"Claw","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/clawgame_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/clawgame_l_2x.webp","line":"Turn into a plushie in an arcade claw game.","prompt":"The person as a plushie prize inside an arcade claw machine, surrounded by other toys under bright cabinet lights, the claw hovering just above."},
  {"id":"images-page-handdrawn","name":"Pastel","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/handdrawn_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/handdrawn_l_2x.webp","line":"Imagine yourself in a pastel-colored world.","prompt":"The person in a pastel-coloured world: soft pinks, mint and lilac sets, a matching pastel outfit, a dreamy hand-drawn feel."},
  {"id":"images-page-lavender","name":"Lavender","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/lavender_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/lavender_l_2x.webp","line":"Picture yourself in a lavender field.","prompt":"The person standing in a lavender field in full bloom at golden hour, rows of purple stretching to the hills, soft focus and warm light."},
  {"id":"images-page-watercolor","name":"Paint","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/watercolor_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/watercolor_l_2x.webp","line":"Turn into a watercolor painting.","prompt":"A loose watercolor painting of the person, soft washes and gentle colour bleeds, visible paper texture and a few confident brush lines."},
  {"id":"images-page-polymerclay","name":"Clay","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/polymerclay_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/polymerclay_l_2x.webp","line":"Turn into a clay character.","prompt":"The person as a polymer-clay character: smooth sculpted shapes, tiny clay accessories and fingerprint texture, posed in a miniature handmade set."},
  {"id":"images-page-mural","name":"Mural","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/mural_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/mural_l_2x.webp","line":"Turn into a colorful urban mural.","prompt":"A colourful urban mural of the person on a brick wall: bold spray-painted shapes, bright blocks of colour, a few paint cans at the foot of the wall."},
  {"id":"images-page-bento","name":"Bento","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/bento_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/bento_l_2x.webp","line":"Turn into a tiny figure in a bento box.","prompt":"The person as a tiny figure sitting in a Japanese bento box among rice, sushi, tamagoyaki and vegetables, shot from above in soft daylight."},
  {"id":"images-page-monstera","name":"Monstera","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/monstera_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/monstera_l_2x.webp","line":"Picture yourself in a monstera garden.","prompt":"The person in a lush monstera garden, surrounded by giant glossy leaves, dappled green light and a humid, tropical atmosphere."},
  {"id":"images-page-70spulp","name":"Pulp","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/70spulp_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/70spulp_l_2x.webp","line":"Imagine yourself on a 70s pulp movie poster.","prompt":"The person on a 1970s pulp movie poster: a dramatic painted illustration, bold title lettering, explosive action behind them and worn, folded paper."},
  {"id":"images-page-ROW_studio","name":"Studio","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/ROW_studio_thumbnail.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/ROW_studio_modal.webp","line":"Picture yourself at a pro studio photoshoot.","prompt":"The person at a professional studio photoshoot: a seamless backdrop, strobe lights and softboxes, a striking fashion-editorial pose."},
  {"id":"images-page-90ssitcom","name":"Sitcom","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/90ssitcom_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/90ssitcom_l_2x.webp","line":"Imagine yourself as the star of a 90s sitcom.","prompt":"The person as the star of a 1990s sitcom: a bright living-room set, a ’90s outfit and the warm, slightly soft look of the show’s opening credits."},
  {"id":"images-page-yogi","name":"Yogi","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/yogi_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/yogi_l_2x.webp","line":"Picture yourself as a balancing yogi.","prompt":"The person as a yogi holding a balancing pose on a rock at sunrise, calm and strong, mist over the water behind them."},
  {"id":"images-page-characters","name":"Theme park","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/characters_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/characters_l_2x.webp","line":"Imagine yourself as an 80s theme park mascot.","prompt":"The person as a cheerful 1980s theme park mascot in a big costume, waving in a retro park, faded film colours and a sunny sky."},
  {"id":"images-page-bronze","name":"Bronze","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/bronze_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/bronze_l_2x.webp","line":"Turn into a bronze sculpture.","prompt":"A polished bronze sculpture of the person on a stone plinth, with a warm patina and gallery spotlights."},
  {"id":"images-page-zengarden","name":"Zen","image":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/zengarden_p_2x.webp","preview":"https://www.gstatic.com/bard-robin-zs/discovery/discosurf/zengarden_l_2x.webp","line":"Imagine yourself in a futuristic zen garden.","prompt":"The person in a futuristic zen garden: raked white sand, sculpted stones, sleek minimal architecture and soft diffused light."},
];
