/**
 * The creation tools' zero-state galleries, as Gemini shows them (captured Oct 2026 off the live
 * app by tools/ui-research/scrapers/gemini/media-tools-2026/06-gallery.cjs and 07-music-previews.cjs;
 * regenerate with tools/media/gen-media-templates.cjs). Names, art, previews, tabs and each
 * template's prompt-box placeholder are Gemini's; `prompt` is Willow's own, because the style a
 * template asks for is not visible in Gemini's client. Gemini serves the set from its server and
 * reshuffles it, so this is a snapshot.
 */
export interface MediaTemplate {
  id: string;
  name: string;
  /** The card art, also the prompt-box tile. */
  image: string;
  /** Video: the animated art the card swaps to under the pointer. */
  hoverImage?: string;
  /** Music: the "Preview track" clip. */
  audio?: string;
  /** What the prompt box asks for once the template is picked. */
  placeholder: string;
  /** The style the generator is asked for. */
  prompt: string;
  /** Tabs besides All. */
  tabs: string[];
}

export type GalleryTool = 'images' | 'video' | 'music';

export const MEDIA_GALLERY: Record<GalleryTool, { tabs: string[]; templates: MediaTemplate[] }> = {
  images: {
    tabs: ["All","Restyle","Imagine"],
    templates: [
      {"id":"image-80s-rewind","name":"'80s rewind","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/2026Q3/80s/02cd5ov4lj9e8.webp","placeholder":"Add a photo for an instant makeover","prompt":"Give the person in the photo a full 1980s makeover: big teased hair, bold eyeshadow and blush, neon and denim, as a candid flash photo with warm film grain.","tabs":["Restyle"]},
      {"id":"image-80s-glam","name":"'80s glam","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/2026Q3/80s/41s31uhohpr08.webp","placeholder":"Add a photo to get a glamorous portrait","prompt":"Turn the photo into a glamorous 1980s studio portrait: soft-focus haze, shoulder pads, glossy lips, a sparkle backdrop and a dreamy pastel gradient.","tabs":["Restyle"]},
      {"id":"image-80s-vacation","name":"'80s vacation","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/2026Q3/80s/2740hhfoh4910.webp","placeholder":"Add a photo to see yourself on holiday in the '80s","prompt":"Put the person on a 1980s holiday: a sunny resort, retro swimwear and sunglasses, faded Kodachrome colour and a white snapshot border.","tabs":["Restyle"]},
      {"id":"image-80s-disco","name":"'80s disco","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/2026Q3/80s/7lobmjbtkvp90.webp","placeholder":"Add a photo to join an '80s disco night","prompt":"Put the person on a 1980s disco floor: mirror-ball light, neon haze, sequins and big hair, shot like a flash-lit party photo.","tabs":["Restyle"]},
      {"id":"image-monochrome","name":"Monochrome","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/monochrome_2.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the photo as a high-contrast black-and-white fine-art portrait with deep blacks, crisp highlights and fine film grain.","tabs":["Restyle"]},
      {"id":"image-runway","name":"Runway","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/runway.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the person mid-stride on a fashion-week runway in a striking couture outfit, with photographers’ flashes and a blurred audience.","tabs":["Restyle","Imagine"]},
      {"id":"image-technicolor","name":"Technicolor","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/technicolor.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the photo in the saturated three-strip Technicolor look of 1950s cinema: lush reds and teals, a soft glow, studio light.","tabs":["Restyle"]},
      {"id":"image-light-beams","name":"Light beams","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/light_beams.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the photo with dramatic beams of light cutting through haze, throwing bold shafts and shadows across the subject.","tabs":[]},
      {"id":"image-moody","name":"Moody","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/moody.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the photo with a moody, low-key cinematic grade: deep shadows, muted colour, one soft light source, a quiet atmosphere.","tabs":["Restyle"]},
      {"id":"image-enamel-pin","name":"Enamel pin","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/enamel_pin.webp","placeholder":"Add a photo and describe changes","prompt":"Turn the subject into a glossy enamel pin with gold metal outlines and flat bright colours, on a fabric backing, shot as a product photo.","tabs":["Restyle","Imagine"]},
      {"id":"image-sketch","name":"Sketch","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/sketch.webp","placeholder":"Add a photo and describe changes","prompt":"Turn the photo into a detailed graphite pencil sketch on textured paper, with cross-hatching and a few loose construction lines.","tabs":["Restyle"]},
      {"id":"image-color-block","name":"Color block","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/color_block.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the photo as a bold colour-block portrait: flat saturated blocks of colour, graphic shapes, a clean modern backdrop.","tabs":["Restyle"]},
      {"id":"image-oil-painting","name":"Oil painting","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/oil_painting.webp","placeholder":"Add a photo and describe changes","prompt":"Repaint the photo as a classical oil painting with visible brushwork, rich glazes and the warm chiaroscuro of an old-master portrait.","tabs":["Restyle"]},
      {"id":"image-mythic-fighter","name":"Mythic fighter","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/mythic_fighter.webp","placeholder":"Add a photo and describe changes","prompt":"Transform the person into an epic mythic warrior in ornate armour, in a battle scene lit by storm light and flying sparks.","tabs":["Imagine"]},
      {"id":"image-soft-portrait","name":"Soft portrait","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/depth_of_field.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the photo as a soft, flattering portrait: diffused window light, gentle skin tones, shallow depth of field, a calm palette.","tabs":["Restyle"]},
      {"id":"image-dynamite","name":"Dynamite","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/dynamite_2.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the photo as an explosive action poster: a fiery blast behind the subject, flying debris and sparks, a heroic low angle.","tabs":["Restyle"]},
      {"id":"image-surreal","name":"Surreal","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/surreal_2.webp","placeholder":"Add a photo and describe changes","prompt":"Turn the photo into a surreal dreamscape: impossible architecture, floating objects and melting forms in a vast desert.","tabs":["Imagine"]},
      {"id":"image-steampunk","name":"Steampunk","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/steampunk.webp","placeholder":"Add a photo and describe changes","prompt":"Reimagine the subject in a steampunk world: brass gears, goggles, Victorian clothing, airships and warm smoky light.","tabs":["Restyle","Imagine"]},
      {"id":"image-salon","name":"Salon","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/salon_2.webp","placeholder":"Add a photo and describe changes","prompt":"Give the person a fresh salon look, a polished new cut and styling, photographed in a bright salon against a clean backdrop.","tabs":["Restyle","Imagine"]},
      {"id":"image-cinematic","name":"Cinematic","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/cinematic.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the photo as a still from a big-budget film: anamorphic widescreen framing, a teal-and-orange grade, atmospheric haze.","tabs":["Restyle"]},
      {"id":"image-cyborg","name":"Cyborg","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/cyborg.webp","placeholder":"Add a photo and describe changes","prompt":"Transform the subject into a sleek cyborg with exposed circuitry, chrome plating and glowing details, in a high-tech lab.","tabs":["Imagine"]},
      {"id":"image-old-cartoon","name":"Old cartoon","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/old_cartoon.webp","placeholder":"Add a photo and describe changes","prompt":"Redraw the scene as a 1930s rubber-hose cartoon: black-and-white ink, bouncy limbs, pie-cut eyes and film scratches.","tabs":["Imagine"]},
      {"id":"image-sunrise","name":"Sunrise","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/sunrise.webp","placeholder":"Add a photo and describe changes","prompt":"Restyle the photo in golden sunrise light: long warm shadows, a lens flare, soft mist and a glowing sky.","tabs":["Restyle"]},
      {"id":"image-gothic-clay","name":"Gothic clay","image":"https://www.gstatic.com/bard-robin-zs/media_gen_templates/image_templates/rect/gothic_clay_2.webp","placeholder":"Add a photo and describe changes","prompt":"Turn the subject into a stop-motion clay figure on a gothic set: pale clay, dark whimsical architecture, moody light.","tabs":["Imagine"]},
    ],
  },
  video: {
    tabs: ["All","Restyle","Celebration","Creators"],
    templates: [
      {"id":"video-career-day","name":"Career day","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/rect/career_day.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/career_day.webp","placeholder":"Try on different careers","prompt":"A quick montage of the person trying on different careers (astronaut, chef, surgeon, firefighter), a new outfit and setting in each shot.","tabs":[]},
      {"id":"video-video-game","name":"Video game","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/video_game_2.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/video_game_3.webp","placeholder":"Become a game character","prompt":"Turn the person into a character in a stylised 3D video game, with a HUD, a level-up moment and game-world scenery.","tabs":["Celebration"]},
      {"id":"video-edible-city","name":"Edible city","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/rect/new/edible_city.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/edible_city.webp","placeholder":"Add photos or describe your scene","prompt":"A city built entirely from food (cake towers, candy cars, chocolate rivers) seen in one slow sweeping camera move.","tabs":[]},
      {"id":"video-noir","name":"Noir","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/noir.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/noir_2.webp","placeholder":"Give any scene a moody look","prompt":"Give the scene a 1940s film-noir look: black and white, venetian-blind shadows, rain-slick streets and a slow push-in.","tabs":[]},
      {"id":"video-pop-up-card","name":"Pop-up card","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/rect/new/popup_card.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/popup_card.webp","placeholder":"Describe your card","prompt":"A paper pop-up greeting card opening, its layers unfolding into a 3D scene around the message.","tabs":["Celebration"]},
      {"id":"video-360-photo-booth","name":"360 photo booth","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/rect/360_photo_booth.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/360_photo_booth.webp","placeholder":"Bring some photos to life","prompt":"A 360-degree photo-booth shot: the camera orbits the subject as they pose and the background lights pulse.","tabs":[]},
      {"id":"video-science-concept","name":"Science concept","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/rect/science_concept.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/science_concept.webp","placeholder":"Visualize a science concept","prompt":"A clear animated explanation of the science concept, with labelled 3D models and smooth camera moves.","tabs":["Creators"]},
      {"id":"video-pixelate","name":"Pixelate","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/pixelate.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/pixelate_2.webp","placeholder":"Pixelate your world","prompt":"The scene breaks into chunky pixels and resolves into an animated 16-bit version of itself.","tabs":["Restyle"]},
      {"id":"video-montage","name":"Montage","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/montage.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/montage_2.webp","placeholder":"Add photos for your montage","prompt":"An energetic montage of the photos with quick cuts, light leaks and gentle push-ins.","tabs":["Creators"]},
      {"id":"video-decades-fashion","name":"Decades fashion","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/decades_fashion.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/decades_fashion_2.webp","placeholder":"See yourself in different decades","prompt":"The person cycles through fashion from the 1920s to today, outfit and setting changing with each decade.","tabs":[]},
      {"id":"video-tiny-world","name":"Tiny world","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/rect/new/tiny_world.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/tiny_world.webp","placeholder":"Turn your world tiny","prompt":"Turn the scene into a tilt-shift miniature, with tiny people and cars moving like toys.","tabs":[]},
      {"id":"video-origami","name":"Origami","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/origami.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/origami_2.webp","placeholder":"Fold your world into paper","prompt":"Everything in the scene is folded paper, animating with crisp origami folds.","tabs":["Restyle"]},
      {"id":"video-talking-pets","name":"Talking pets","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/talking_pets.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/talking_pets_2.webp","placeholder":"Add a photo of your pet","prompt":"The pet in the photo talks to the camera with natural mouth movement and expressive reactions.","tabs":[]},
      {"id":"video-chaotic-vlog","name":"Chaotic vlog","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/rect/chaotic_vlog.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/chaotic_vlog.webp","placeholder":"What's your vlog about?","prompt":"A handheld, chaotic vlog: fast cuts, whip pans, on-screen captions and a host talking to camera.","tabs":["Creators"]},
      {"id":"video-birthday-balloons","name":"Birthday balloons","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/rect/new/birthday_balloons.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/birthday_balloons.webp","placeholder":"Wish someone a happy birthday","prompt":"Shiny foil balloons spell out the birthday message, bobbing in a room full of confetti.","tabs":["Celebration"]},
      {"id":"video-analyze-me","name":"Analyze me","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/analyze_me.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/analyze_me_2.webp","placeholder":"Add a photo or description","prompt":"A playful sci-fi scan of the subject, with holographic readouts and analysis overlays.","tabs":[]},
      {"id":"video-walkthrough","name":"Walkthrough","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/rect/new/walkthough.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/walkthough.webp","placeholder":"Add photos or describe your scene","prompt":"A smooth first-person walkthrough of the space, gliding from room to room.","tabs":["Creators"]},
      {"id":"video-logo-reveal","name":"Logo reveal","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/rect/new/logo_reveal.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/logo_reveal.webp","placeholder":"Add photos or describe your logo","prompt":"A polished logo reveal: elements assemble with light streaks and a glint, then hold on the logo.","tabs":["Creators"]},
      {"id":"video-moon","name":"Moon","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/moon.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/moon.webp","placeholder":"See yourself on the moon","prompt":"The person walks on the Moon in a spacesuit, Earth rising behind them, dust drifting in slow motion.","tabs":[]},
      {"id":"video-anniversary","name":"Anniversary","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/rect/new/anniversary.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/anniversary.webp","placeholder":"What are you celebrating?","prompt":"A warm anniversary video: soft light, candid moments and a heartfelt message.","tabs":["Celebration"]},
      {"id":"video-product-showcase","name":"Product showcase","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/rect/new/product_showcase.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/product_showcase.webp","placeholder":"Add photos of your product","prompt":"A premium product showcase: a slow orbit on a clean backdrop, studio light, macro detail shots.","tabs":["Creators"]},
      {"id":"video-plush-world","name":"Plush world","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/rect/plush_world.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/plush_world.webp","placeholder":"Make your world more plush","prompt":"Everything in the scene becomes soft felt and plush, gently bouncing and squishing.","tabs":[]},
      {"id":"video-anime","name":"Anime","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/anime.webp","placeholder":"Transform a scene into anime","prompt":"Transform the scene into hand-drawn anime with cel shading, speed lines and dramatic light.","tabs":["Restyle"]},
      {"id":"video-cut-paper","name":"Cut paper","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/cut_paper.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/cut_paper_2.webp","placeholder":"What text do you want animated?","prompt":"The text animates in layered cut paper, pieces sliding and popping into place.","tabs":["Creators"]},
      {"id":"video-8-bit-adventure","name":"8-bit adventure","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/8bit_adventure_2.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/8bit_adventure_3.webp","placeholder":"Describe your 8-bit scene","prompt":"An 8-bit side-scrolling adventure: chunky sprites, a scrolling level and chiptune energy.","tabs":[]},
      {"id":"video-meme-me","name":"Meme me","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/meme_me.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/meme_me_3.webp","placeholder":"Add yourself to a meme","prompt":"Recreate a classic meme format starring the person, timed for comedy.","tabs":[]},
      {"id":"video-80s-music-video","name":"80's music video","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/80s_music_video.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/80s_music_video.webp","placeholder":"Rewind any scene to the 80s","prompt":"Rewind the scene into a 1980s music video: VHS grain, neon grids, smoke and dramatic slow motion.","tabs":[]},
      {"id":"video-comic-book","name":"Comic book","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/comic_book_2.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/comic_book_3.webp","placeholder":"Become a comic book hero","prompt":"Turn the person into a comic-book hero: halftone dots, ink outlines, action panels and sound effects.","tabs":[]},
      {"id":"video-indie-pastel","name":"Indie pastel","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/indie_pastel.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/indie_pastel_3.webp","placeholder":"Describe your indie film scene","prompt":"A symmetrical indie-film scene in soft pastels, centred framing and deadpan charm, opening on a chapter title card.","tabs":[]},
      {"id":"video-step-into-history","name":"Step into history","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/rect/step_into_history.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/step_into_history.webp","placeholder":"Who do you want to meet?","prompt":"The person steps into a historical moment and meets the figure they name, in period setting and costume.","tabs":[]},
      {"id":"video-doodle-effects","name":"Doodle effects","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/doodle_effects.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/doodle_effects_2.webp","placeholder":"Upload a video to add effects","prompt":"Add hand-drawn animated doodles (sparkles, arrows, scribbles) that track the action in the video.","tabs":["Restyle"]},
      {"id":"video-party-invite","name":"Party invite","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final_image/rect/party_invite_1.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/io_final/party_invite_1.webp","placeholder":"Describe your event","prompt":"An animated party invitation with the event details, festive motion and confetti.","tabs":["Celebration"]},
      {"id":"video-storybook","name":"Storybook","image":"https://www.gstatic.com/bard-robin-zs/aura/omni/rect/new/storybook.webp","hoverImage":"https://www.gstatic.com/bard-robin-zs/aura/omni/webp/video/storybook.webp","placeholder":"What's your story about?","prompt":"A storybook come to life: illustrated pages turn and the characters animate on them.","tabs":[]},
    ],
  },
  music: {
    tabs: ["All","Celebration","Creators"],
    templates: [
      {"id":"music-hometown-tribute","name":"Hometown tribute","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/hometown_tribute_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/hometown_tribute.mp3","placeholder":"Describe your hometown","prompt":"A heartfelt anthem for the user’s hometown, its streets, people and memories, with a sing-along chorus.","tabs":[]},
      {"id":"music-speech-to-song","name":"Speech to song","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/speech_to_track_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/speech_to_track.mp3","placeholder":"Turn a speech into a song","prompt":"Set the user’s speech to music, keeping their words as the lyrics over a fitting backing track.","tabs":[]},
      {"id":"music-happy-birthday","name":"Happy birthday","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/happy_birthday_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/happy_birthday_v2.mp3","placeholder":"Describe who is celebrating a birthday","prompt":"An upbeat birthday song that names the person celebrating.","tabs":["Celebration"]},
      {"id":"music-comedy","name":"Comedy","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/comedy_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/comedy_v2.mp3","placeholder":"What’s your comedy track about?","prompt":"A funny song with witty, punchy lyrics about the user’s topic.","tabs":[]},
      {"id":"music-sports-recap","name":"Sports recap","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/sports_recap_v3.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/sports_recap.mp3","placeholder":"Which game are you following?","prompt":"A high-energy recap track that narrates the game’s big moments like a stadium anthem.","tabs":[]},
      {"id":"music-weather-report","name":"Weather report","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/weather_report_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/weather_report_v2.mp3","placeholder":"What’s your location?","prompt":"A playful jingle that sings the weather report for the user’s location.","tabs":[]},
      {"id":"music-love-story","name":"Love story","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/love_story_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/love_story.mp3","placeholder":"Describe your love story","prompt":"A romantic ballad that tells the user’s love story.","tabs":["Celebration"]},
      {"id":"music-party-invite","name":"Party invite","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/party_invite_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/party_invite.mp3","placeholder":"Describe the event you’re hosting","prompt":"A catchy invitation song with the event’s details in the lyrics.","tabs":["Celebration"]},
      {"id":"music-soundscape","name":"Soundscape","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/soundscape_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/soundscape.mp3","placeholder":"Describe the setting or add a photo","prompt":"An immersive ambient soundscape of the setting, without vocals.","tabs":["Creators"]},
      {"id":"music-intro-music","name":"Intro music","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/intro_music_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/intro_music.mp3","placeholder":"Describe what you’re introducing","prompt":"A short, punchy intro theme for what the user is introducing.","tabs":["Creators"]},
      {"id":"music-memorize-something","name":"Memorize something","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/memorize_something_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/memorize_something_v2.mp3","placeholder":"What do you want to memorize?","prompt":"A catchy, repetitive song with the facts to memorise in its lyrics.","tabs":[]},
      {"id":"music-background-music","name":"Background music","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/background_music_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/background_music.mp3","placeholder":"What’s the background music for?","prompt":"Unobtrusive instrumental background music that suits what it is for.","tabs":["Creators"]},
      {"id":"music-team-anthem","name":"Team anthem","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/team_anthem_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/team_anthem.mp3","placeholder":"Describe your team","prompt":"A rousing team anthem with a chantable chorus.","tabs":[]},
      {"id":"music-text-messages","name":"Text messages","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/text_messages_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/text_messages_v2.mp3","placeholder":"Add photos of your text messages","prompt":"Turn the text-message conversation into a song, using the messages as lyrics.","tabs":[]},
      {"id":"music-brand-jingle","name":"Brand jingle","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/brand_jingle_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/brand_jingle.mp3","placeholder":"Describe what your jingle is about","prompt":"A short, memorable brand jingle built on one hook.","tabs":["Creators"]},
      {"id":"music-birthday-roast","name":"Birthday roast","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/birthday_roast_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/birthday_roast.mp3","placeholder":"Describe who you’re roasting","prompt":"A cheeky birthday roast song, teasing but affectionate.","tabs":["Celebration"]},
      {"id":"music-ode-to-your-pet","name":"Ode to your pet","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/ode_to_your_pet_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/ode_to_your_pet.mp3","placeholder":"Describe your pet","prompt":"A sweet ode to the user’s pet and its quirks.","tabs":[]},
      {"id":"music-rap-battle","name":"Rap battle","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/rap_battle_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/rap_battle.mp3","placeholder":"Who’s battling and why?","prompt":"A back-and-forth rap battle between the two sides, with clever bars.","tabs":[]},
      {"id":"music-ringtone","name":"Ringtone","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/ringtone_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/ringtone.mp3","placeholder":"Describe the mood you’re going for","prompt":"A short, loopable ringtone in the mood described.","tabs":[]},
      {"id":"music-business-promo","name":"Business promo","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/business_promo_v3.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/business_promo.mp3","placeholder":"Describe your business","prompt":"An upbeat promo track for the business that names what it offers.","tabs":["Creators"]},
      {"id":"music-montage","name":"Montage","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/montage_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/montage.mp3","placeholder":"What’s your montage of?","prompt":"A montage track that builds from calm to triumphant.","tabs":["Creators"]},
      {"id":"music-streaming","name":"Streaming","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/streaming_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/streaming.mp3","placeholder":"Describe your stream’s mood","prompt":"A looping, vocal-free backing track for a stream in the mood described.","tabs":["Creators"]},
      {"id":"music-say-it-with-a-track","name":"Say it with a track","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/say_it_with_a_track_v2.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/say_it_with_a_track.mp3","placeholder":"What’s your message and who is it for?","prompt":"A song that delivers the user’s message to the person it is for.","tabs":["Celebration"]},
      {"id":"music-friend-appreciation","name":"Friend appreciation","image":"https://www.gstatic.com/bard-robin-zs/musicgen/image_assets_v2/webp/friend_appreciation_v3.webp","audio":"https://www.gstatic.com/bard-robin-zs/musicgen/audio_assets_v2/friend_appreciation.mp3","placeholder":"Describe your friend","prompt":"A warm song of appreciation for the user’s friend.","tabs":["Celebration"]},
    ],
  },
};

export const isGalleryTool = (tool: string | null | undefined): tool is GalleryTool =>
  tool === 'images' || tool === 'video' || tool === 'music';
