export const buttonRadiusBySize = {
  onboardingAction: "rounded-full",
  activityOption: "rounded-full",
  auth: "rounded-full",
  giftCard: "rounded-full",
  compact: "rounded-button-action",
  cardAction: "rounded-full",
  default: "rounded-full",
  actionSm: "rounded-full",
  sidebarOffer: "rounded-full",
  dialog: "rounded-full",
  dialogAction: "rounded-full",
  modalPrimary: "rounded-full",
  pageAction: "rounded-full",
  formDisclosure: "rounded-xl",
  formValue: "rounded-md",
  recoveryAction: "rounded-full",
  panelAction: "rounded-full",
  detailAction: "rounded-full",
  beaconAction: "rounded-full",
  expressiveBeaconAction: "rounded-full",
  takeoverHeroAction: "rounded-full",
  promotionalAction: "rounded-full",
  promotionalLink: "rounded-full",
  workNux: "rounded-full",
  workPopover: "rounded-full",
  beaconCarousel: "rounded-full",
  conversationFollowup: "rounded-full",
  conversationPill: "rounded-full",
  conversationPillAction: "rounded-full",
  actionChip: "rounded-full",
  actionChipWithIcon: "rounded-full",
  paginationDot: "rounded-full",
  dialogGhost: "rounded-button-action",
  avatarGroup: "rounded-full",
  avatarGroupAction: "rounded-full",
  entityHeader: "rounded-xl",
  entityRowAction: "rounded-full",
  dragHandle: "rounded-lg",
  formatToolbar: "rounded-md",
  formatToolbarIcon: "rounded-md",
  field: "rounded-md",
  fieldControl: "rounded-none",
  fieldSegment: "rounded-md",
  icon: "rounded-full electron:rounded-md",
  iconCircle: "rounded-full",
  iconCircleLg: "rounded-full",
  iconTouch: "rounded-full",
  iconCircleSm: "rounded-full",
  iconLarge: "rounded-2xl",
  iconMd: "rounded-md",
  iconSm: "rounded-md",
  inputSegment: "rounded-none",
  inputSelect: "rounded-none",
  inputControl: "rounded-xl",
  imageToolbar: "rounded-full",
  imageAction: "rounded-lg",
  imageActionIcon: "rounded-full",
  floatingAction: "rounded-full",
  inline: "rounded-none",
  inputIcon: "rounded-s-lg rounded-e-none",
  large: "rounded-full",
  medium: "rounded-button-action",
  menuRow: "rounded-lg",
  settingsSelect: "rounded-md",
  settingsOption: "rounded-lg",
  settingsAction: "rounded-button-action",
  composer: "rounded-full",
  composerWithBadge: "rounded-full",
  composerPill: "rounded-full",
  composerAuxiliary: "rounded-full",
  composerPermissions: "rounded-full",
  composerSm: "rounded-full",
  composerSmLabel: "rounded-full",
  shareDestination: "rounded-full",
  surveyOption: "rounded-lg",
  surveyCard: "rounded-xl",
  tabStripAction: "rounded-lg",
  toolbar: "rounded-button-toolbar",
  toolbarLabel: "rounded-lg",
  headerUpsell: "rounded-md"
};

export const buttonRadiusClasses = {
  full: "rounded-full",
  messageBubble: "rounded-[var(--message-bubble-radius,var(--radius-full))]",
  extraLarge: "rounded-2xl",
  large: "rounded-lg",
  small: "rounded-md"
};

export const buttonColorClasses = {
  activity: "border-transparent bg-activity-control text-activity-control not-disabled:not-aria-disabled:hover:bg-activity-control-hover not-disabled:not-aria-disabled:hover:text-activity-control-active not-disabled:not-aria-disabled:data-[native-hovered=true]:bg-activity-control-hover not-disabled:not-aria-disabled:data-[native-hovered=true]:text-activity-control-active aria-pressed:bg-activity-control-hover aria-pressed:text-activity-control-active",
  activityStop: "border-transparent bg-activity-control text-activity-control not-disabled:not-aria-disabled:hover:bg-activity-stop-hover not-disabled:not-aria-disabled:hover:text-activity-control-active not-disabled:not-aria-disabled:data-[native-hovered=true]:bg-activity-stop-hover not-disabled:not-aria-disabled:data-[native-hovered=true]:text-activity-control-active",
  activitySuccess: "border-transparent bg-[light-dark(var(--green-50),var(--green-900))] text-[color:light-dark(var(--green-400),var(--green-300))] not-disabled:not-aria-disabled:hover:bg-[light-dark(var(--green-300),var(--green-500))] not-disabled:not-aria-disabled:hover:text-white not-disabled:not-aria-disabled:data-[native-hovered=true]:bg-[light-dark(var(--green-300),var(--green-500))] not-disabled:not-aria-disabled:data-[native-hovered=true]:text-white",
  accent: "bg-info-solid not-disabled:not-aria-disabled:hover:bg-info-solid/90 data-[state=open]:bg-info-solid/90 text-info-solid border-transparent",
  accentInverse: "bg-info-solid not-disabled:not-aria-disabled:hover:bg-info-solid/90 data-[state=open]:bg-info-solid/90 text-inverse border-transparent",
  accentSubtle: "bg-text-info/10 not-disabled:not-aria-disabled:hover:bg-text-info/15 data-[state=open]:bg-text-info/15 text-info border-transparent",
  conversationAccentSubtle: "bg-[var(--conversation-accent,var(--color-text-info))]/10 not-disabled:not-aria-disabled:hover:bg-[var(--conversation-accent,var(--color-text-info))]/15 data-[state=open]:bg-[var(--conversation-accent,var(--color-text-info))]/15 text-[color:var(--conversation-accent-text,var(--color-text-info))] border-transparent",
  headerUpgrade: "border-transparent bg-transparent text-info-ghost not-disabled:not-aria-disabled:hover:bg-info-ghost-hover focus-visible:bg-info-ghost-hover data-[state=open]:bg-info-ghost-hover",
  upgrade: "border-transparent bg-[light-dark(var(--blue-a25),--alpha(var(--blue-100)/15%))] text-[color:light-dark(var(--blue-500),var(--blue-50))] not-disabled:not-aria-disabled:hover:bg-[light-dark(--alpha(var(--blue-400)/9%),--alpha(var(--blue-100)/20%))] data-[state=open]:bg-[light-dark(--alpha(var(--blue-400)/9%),--alpha(var(--blue-100)/20%))]",
  composerPrimary: "bg-composer-primary not-disabled:not-aria-disabled:hover:bg-composer-primary/90 data-[state=open]:bg-composer-primary/90 text-composer-primary border-transparent",
  composerSurface: "border-transparent bg-(--color-background-primary-soft)/90 text-default shadow-(--elevation-composer) dark:bg-surface-elevated dark:shadow-(--elevation-composer-dark) not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover light:[:where(:root[data-codex-os=win32].electron-opaque)_&]:bg-(--color-background-primary-soft) forced-colors:shadow-none forced-colors:outline forced-colors:outline-[CanvasText]",
  cardAction: "border-subtle bg-surface-card text-default not-disabled:not-aria-disabled:active:opacity-80",
  successOutline: "border-text-success-solid/20 bg-transparent text-success-solid not-disabled:not-aria-disabled:hover:bg-text-success-solid/10",
  successSolid: "bg-success-solid not-disabled:not-aria-disabled:hover:bg-success-solid-hover data-[state=open]:bg-success-solid-hover text-success-solid border-transparent",
  danger: "bg-chart-red/10 not-disabled:not-aria-disabled:hover:bg-chart-red/20 text-chart-red border-transparent",
  dangerSolid: "bg-danger-solid not-disabled:not-aria-disabled:hover:bg-danger-solid/90 text-danger-solid border-transparent",
  dangerOutline: "border-danger bg-transparent text-danger not-disabled:not-aria-disabled:hover:bg-danger-solid/10",
  ghost: "text-tertiary not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover border-transparent",
  disclosure: "border-transparent bg-transparent text-tertiary",
  blockAction: "text-tertiary not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover not-disabled:not-aria-disabled:hover:text-default data-[state=open]:bg-primary-ghost-hover border-transparent",
  ghostAccent: "text-info not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover border-transparent",
  ghostSubtle: "text-default not-disabled:not-aria-disabled:hover:bg-primary-soft-alpha data-[state=open]:bg-primary-soft-alpha border-0",
  ghostAccentSubtle: "text-info not-disabled:not-aria-disabled:hover:bg-primary-soft-alpha data-[state=open]:bg-primary-soft-alpha border-0",
  ghostOutline: "border-transparent text-tertiary not-disabled:not-aria-disabled:hover:border-default not-disabled:not-aria-disabled:hover:bg-surface not-disabled:not-aria-disabled:hover:text-default not-disabled:not-aria-disabled:hover:shadow-sm data-[state=open]:border-default data-[state=open]:bg-surface data-[state=open]:text-default data-[state=open]:shadow-sm",
  ghostSecondary: "text-secondary not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover border-transparent",
  ghostDanger: "border-transparent text-default not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover not-disabled:not-aria-disabled:hover:text-danger focus-visible:bg-primary-ghost-hover focus-visible:text-danger",
  outlineActive: "border-default bg-text/10 not-disabled:not-aria-disabled:hover:bg-text/15 data-[state=open]:bg-text/15 border",
  ghostActive: "text-default not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover border-transparent",
  toolbar: "text-(--color-text-toolbar-action) not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover border-transparent",
  ghostMuted: "not-disabled:not-aria-disabled:hover:bg-transparent data-[state=open]:bg-transparent hover:text-default border-transparent",
  ghostUserMessage: "text-user-message not-disabled:not-aria-disabled:hover:bg-transparent data-[state=open]:bg-transparent border-transparent",
  ghostTertiary: "text-tertiary not-disabled:not-aria-disabled:hover:bg-transparent data-[state=open]:bg-transparent not-disabled:not-aria-disabled:hover:text-default border-transparent",
  mediaSolid: "border-transparent bg-media-foreground text-media-background not-disabled:not-aria-disabled:hover:bg-media-foreground/90 data-[state=open]:bg-media-foreground/90",
  mediaSubtle: "border-media-foreground/20 bg-media-control-background text-media-foreground not-disabled:not-aria-disabled:hover:bg-media-control-hover data-[state=open]:bg-media-control-hover",
  mediaOverlay: "border-transparent bg-media-control-background text-media-foreground not-disabled:not-aria-disabled:hover:bg-media-control-hover focus:bg-media-control-hover data-[state=open]:bg-media-control-hover",
  imageSurface: "border-transparent bg-surface text-default not-disabled:not-aria-disabled:hover:bg-surface focus-visible:bg-surface data-[state=open]:bg-surface",
  outline: "border-default bg-primary-soft-alpha not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover border",
  field: "border-default bg-primary-soft-alpha text-default not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover",
  mapSurface: "relative isolate border-transparent bg-surface text-default ring-1 ring-border after:pointer-events-none after:absolute after:inset-0 after:-z-10 after:rounded-[inherit] not-disabled:not-aria-disabled:hover:after:bg-primary-ghost-hover data-[state=open]:after:bg-primary-ghost-hover not-disabled:not-aria-disabled:aria-pressed:hover:after:bg-current/10 aria-pressed:bg-primary-solid aria-pressed:text-primary-solid",
  outlineSurface: "border-default bg-surface not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover border",
  outlineSurfaceRaised: "button-surface-tint border-default bg-surface text-default shadow-sm border-hairline",
  outlineCard: "border-button-outline bg-surface-card text-button-outline not-disabled:not-aria-disabled:hover:bg-button-outline-hover data-[state=open]:bg-button-outline-hover not-disabled:not-aria-disabled:active:opacity-80",
  conversationFollowup: "border-default bg-surface text-default shadow-sm not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover border",
  conversationPill: "border-default bg-surface-card text-default shadow-card not-disabled:not-aria-disabled:hover:border-transparent not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:border-transparent data-[state=open]:bg-primary-ghost-hover dark:border-transparent dark:shadow-none",
  selectTrigger: "border-default bg-surface not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-surface-elevated-secondary data-[state=open]:rounded-t-2xl data-[state=open]:rounded-b-none data-[state=open]:border-b-transparent border",
  outlineGhost: "border-default bg-transparent text-default not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover",
  outlineGhostMuted: "border-default bg-transparent text-tertiary not-disabled:not-aria-disabled:hover:bg-primary-ghost-hover data-[state=open]:bg-primary-ghost-hover",
  outlineSubtle: "border-subtle bg-transparent text-secondary not-disabled:not-aria-disabled:hover:bg-secondary-soft data-[state=open]:bg-secondary-soft",
  surveyCard: "border-subtle bg-transparent text-default not-disabled:not-aria-disabled:not-aria-pressed:hover:bg-secondary-soft aria-pressed:bg-primary-ghost-hover",
  primary: "border-default bg-primary-solid not-disabled:not-aria-disabled:hover:bg-text/80 data-[state=open]:bg-text/80 text-primary-solid",
  chatgptPrimary: "border-transparent bg-primary-solid bg-clip-padding text-primary-solid not-disabled:not-aria-disabled:hover:bg-primary-solid-hover focus-visible:outline focus-visible:outline-offset-2 focus-visible:outline-text",
  shareDestination: "border-transparent bg-transparent text-secondary not-disabled:not-aria-disabled:hover:bg-transparent [&>.share-destination-icon]:bg-text/5 [&>.share-destination-icon]:text-default not-disabled:not-aria-disabled:hover:[&>.share-destination-icon]:bg-text/10 not-disabled:not-aria-disabled:active:[&>.share-destination-icon]:bg-text/10",
  secondary: "text-default bg-text/5 not-disabled:not-aria-disabled:hover:bg-text/10 data-[state=open]:bg-text/10 border-transparent",
  secondarySurface: "button-surface-tint border-default bg-surface text-default",
  tinted: "bg-current/10 not-disabled:not-aria-disabled:hover:bg-current/15 data-[state=open]:bg-current/15 border-transparent",
  segmentedSelected: "text-default bg-segmented-selected not-disabled:not-aria-disabled:hover:bg-segmented-selected-hover data-[state=open]:bg-segmented-selected-hover border-transparent",
  segmentedInsetSelected: "border-transparent bg-surface text-default shadow-sm not-disabled:not-aria-disabled:hover:bg-surface not-disabled:not-aria-disabled:active:bg-surface data-[state=open]:bg-surface",
  segmentedFormSelected: "border-transparent bg-transparent text-default forced-colors:z-20 forced-colors:outline forced-colors:outline-[Highlight]",
  segmentedFormUnselected: "border-transparent bg-transparent text-secondary not-disabled:not-aria-disabled:hover:text-default data-[state=open]:text-default",
  segmentedFieldSelected: "border-transparent bg-surface text-default inset-ring-1 inset-ring-(--color-border) not-disabled:not-aria-disabled:hover:bg-surface not-disabled:not-aria-disabled:active:bg-surface data-[state=open]:bg-surface"
};

export const buttonSizeClasses = {
  onboardingAction: "h-11.5 justify-center px-4 py-2 text-onboarding-body leading-4 font-medium",
  activityOption: "px-4 py-2 text-[14px] leading-4 font-medium",
  auth: "min-h-13 justify-center gap-2 px-5 py-3 text-base leading-6 font-medium",
  giftCard: "h-12 justify-center px-6 text-base leading-[26px] font-medium",
  compact: "h-6 px-2 py-0 text-xs leading-4",
  cardAction: "h-7 min-h-7 shrink-0 justify-center px-3 py-0 text-sm leading-5 font-medium pointer-coarse:min-h-10",
  composer: "h-token-button-composer px-(--padding-button-composer-inline,calc(var(--spacing)*2)) py-0 text-(length:--text-button-composer,var(--text-sm)) leading-(--line-height-button-composer,18px)",
  composerWithBadge: "h-token-button-composer ps-2 pe-[calc((var(--spacing-token-button-composer)-var(--spacing)*5)/2-1px)] py-0 text-sm leading-[18px]",
  composerPill: "h-(--spacing-token-button-composer) py-0 ps-3 pe-3.5 text-base leading-relaxed",
  composerAuxiliary: "h-token-button-composer px-2 py-0 text-sm leading-[18px]",
  composerPermissions: "h-token-button-composer min-w-token-button-composer justify-center px-1.5 py-0 text-sm leading-[18px]",
  composerSm: "h-token-button-composer-sm px-1.5 py-0 text-sm leading-[18px]",
  composerSmLabel: "h-token-button-composer-sm px-2.5 py-0 text-sm leading-[18px]",
  default: "px-2 py-0.5 text-sm leading-[18px]",
  actionSm: "min-h-7 shrink-0 justify-center px-2.5 py-0 text-xs leading-4 font-medium pointer-coarse:min-h-10",
  sidebarOffer: "min-h-9 shrink-0 justify-center px-4 py-0 text-xs leading-5 font-medium pointer-coarse:min-h-10",
  dialog: "min-h-9 px-3 text-sm font-medium",
  dialogAction: "min-h-9 shrink-0 px-4 text-sm font-medium",
  modalPrimary: "min-h-12 justify-center border-0 px-6 py-3 text-[17px] leading-6 font-medium tracking-[-0.44px]",
  pageAction: "h-8 shrink-0 px-4 py-0 text-sm font-medium browser:h-9",
  formDisclosure: "min-h-12 justify-start gap-1 border-0 px-3.5 py-0 text-form-body font-normal motion-safe:transition-[min-height] motion-safe:duration-relaxed motion-safe:ease-enter-snappy aria-expanded:min-h-10.5",
  formValue: "min-h-10 gap-2 border-0 px-0 py-0 text-form-body font-normal",
  entityRowAction: "min-h-9 shrink-0 justify-center gap-1.5 px-3 py-0 text-onboarding-body font-medium",
  recoveryAction: "min-h-9 shrink-0 justify-center px-3 text-sm leading-5 font-medium",
  panelAction: "min-h-12 shrink-0 justify-center px-8 text-sm leading-5 font-medium",
  detailAction: "min-h-10 justify-center px-4 text-base font-medium",
  beaconAction: "min-h-11 justify-center px-4 text-sm font-medium",
  takeoverHeroAction: "min-h-11 justify-center px-4 text-document leading-5 font-medium",
  expressiveBeaconAction: "min-h-9 justify-center px-5 text-document leading-5 font-medium",
  promotionalAction: "min-h-11.5 justify-center border-0 px-4 py-3.25 text-onboarding-body font-medium",
  promotionalLink: "min-h-9 justify-center border-0 px-0 py-2 text-onboarding-body font-semibold tracking-announcement-body underline decoration-from-font [text-underline-position:from-font]",
  workNux: "min-h-11 min-w-29 justify-center px-6 text-sm font-medium",
  workPopover: "min-h-8 justify-center px-3 text-sm font-normal",
  beaconCarousel: "h-9 min-w-30 justify-center px-4 text-sm font-medium",
  conversationFollowup: "h-10 shrink-0 px-4 py-0 text-sm leading-5",
  conversationPill: "min-h-12 gap-1.5 px-4 py-3 text-base leading-5.5 font-medium",
  conversationPillAction: "min-h-9 px-3 py-0 text-base leading-5.5 font-medium",
  actionChip: "min-h-9 gap-1.5 border-0 py-2 ps-4 pe-2.5 text-[14px] leading-5 font-normal tracking-[-0.14px]",
  actionChipWithIcon: "min-h-11 gap-2 border-0 py-2 ps-2 pe-7 text-[14px] leading-5 font-normal tracking-[-0.14px] has-[>svg:last-child]:pe-2",
  paginationDot: "h-6 w-3.5 shrink-0 justify-center border-0 p-0",
  dialogGhost: "min-h-9 gap-1.5 px-3 text-sm leading-5",
  avatarGroup: "h-full border-0 px-1 text-sm leading-5",
  avatarGroupAction: "h-full border-0 ps-0 pe-3 text-sm leading-5",
  entityHeader: "size-9 shrink-0 justify-center border-0 p-0 pointer-coarse:min-h-10 pointer-coarse:min-w-10",
  dragHandle: "h-7 w-6 shrink-0 justify-center p-0",
  formatToolbar: "h-7 border-0 px-1.5 py-0 text-sm leading-5",
  formatToolbarIcon: "size-7 shrink-0 justify-center border-0 p-0",
  field: "h-8 min-w-0 px-2 py-0 text-sm leading-4.5",
  fieldControl: "h-full w-8 shrink-0 justify-center border-0 p-0",
  fieldSegment: "h-8 min-w-0 justify-center border-0 px-2 py-0 text-sm leading-4.5",
  icon: "electron:p-1 electron:[&>svg]:icon-sm flex items-center justify-center p-0.5",
  iconCircle: "flex size-8 items-center justify-center p-0",
  iconCircleLg: "flex size-9 items-center justify-center p-0",
  iconTouch: "flex size-11 shrink-0 items-center justify-center p-0",
  iconCircleSm: "flex size-5 items-center justify-center p-0",
  iconLarge: "flex size-16 items-center justify-center p-0",
  iconMd: "flex size-5 items-center justify-center p-0.5 [&>svg]:icon-2xs",
  iconSm: "flex h-4 w-4 items-center justify-center p-0.5 [&>svg]:icon-2xs",
  imageToolbar: "h-9 gap-1.5 border-0 px-2 py-0 text-sm leading-5",
  imageAction: "h-9 justify-center border-0 px-3 py-0 text-sm leading-4.5 font-medium",
  imageActionIcon: "size-7 justify-center border-0 p-1",
  floatingAction: "h-14 justify-center overflow-clip border-0 px-6 py-0 text-sm leading-5 font-medium shadow-widget-inline",
  inline: "border-0 p-0",
  inputIcon: "size-9 justify-center border-0 p-0",
  inputSegment: "h-full w-10 shrink-0 justify-center border-e-border p-0",
  inputSelect: "h-full min-w-28 shrink-0 gap-2 border-0 px-3 text-sm",
  inputControl: "h-10 shrink-0 px-4 py-0 text-sm leading-5",
  large: "px-5 py-2 text-base leading-[18px]",
  medium: "px-4 py-1.5 text-base leading-[18px]",
  menuRow: "h-7 px-2 py-0 text-xs leading-4",
  settingsSelect: "h-9 px-2 py-1 text-sm leading-none",
  settingsOption: "min-h-9 gap-2 px-2 py-2 text-sm leading-5",
  settingsAction: "h-7 px-2 py-0 text-base leading-5",
  shareDestination: "min-w-20 flex-col gap-3 border-0 p-0 text-xs max-sm:min-w-0",
  surveyOption: "gap-3 border-0 p-4 text-base leading-6 font-normal",
  surveyCard: "gap-3 p-4 text-sm leading-5 font-normal",
  tabStripAction: "h-[calc(var(--spacing-token-button-composer)+6px)] px-2 py-0 text-base leading-[18px]",
  toolbar: "button-toolbar py-0 text-sm leading-[18px]",
  toolbarLabel: "button-toolbar py-0 text-sm leading-[18px]",
  headerUpsell: "h-8.5 px-3 py-0 text-base leading-5 font-medium pointer-coarse:h-10"
};
