// The stylesheet for StreamingMarkdown, injected once into document.head.
//
// Kept as a string array rather than a .css file because this component ships as
// a self-contained unit: consumers import the component and get its styles with
// it, without a separate CSS import that a bundler might tree-shake or reorder.
// `useInjectStyles` is idempotent — it no-ops if the <style> tag already exists,
// so multiple StreamingMarkdown instances share one injection.
import { useInsertionEffect } from 'react';

const STYLE_ID = 'streaming-markdown-styles';

const STYLE_CSS = [
  '@keyframes smd-fade-in-text {',
  '  from { opacity: 0; }',
  '  to { opacity: 1; }',
  '}',
  '@keyframes smd-media-drift {',
  '  0%, 100% { transform: translate3d(-8%, -5%, 0) scale(1); }',
  '  50% { transform: translate3d(8%, 7%, 0) scale(1.08); }',
  '}',
  '.smd-root {',
  '  display: flex;',
  '  min-width: 0;',
  '  max-width: 100%;',
  '  flex-direction: column;',
  '  gap: 16px;',
  '  color: rgb(227, 227, 227);',
  '  font-family: "Google Sans Flex", "Google Sans", "Helvetica Neue", sans-serif;',
  '  font-size: 17px;',
  '  font-weight: 400;',
  '  line-height: 24px;',
  '  overflow-wrap: break-word;',
  '  text-rendering: auto;',
  '  white-space: pre-wrap;',
  '  word-break: auto-phrase;',
  '}',
  '.smd-root > :first-child { margin-top: 0 !important; }',
  '.smd-root > :last-child { margin-bottom: 0 !important; }',
  '.smd-root p { margin: 0; white-space: pre-wrap; }',
  '.smd-streaming {',
  '  --animation-duration: 400ms;',
  '  --fade-animation-function: ease-out;',
  '}',
  '.smd-streaming .smd-w,',
  '.smd-streaming .smd-h,',
  '.smd-streaming .smd-code-block,',
  '.smd-streaming .smd-svg-preview-block,',
  '.smd-streaming .smd-table-block,',
  '.smd-streaming .smd-media-gallery,',
  '.smd-streaming .smd-rich-resource-group,',
  '.smd-streaming .smd-math-display {',
  '  animation-duration: var(--animation-duration);',
  '  animation-fill-mode: forwards;',
  '  animation-iteration-count: 1;',
  '  animation-name: smd-fade-in-text;',
  '  animation-timing-function: var(--fade-animation-function);',
  '}',
  '.smd-streaming .smd-settled { animation: none; }',
  '.smd-heading {',
  '  color: rgb(227, 227, 227);',
  '  padding: 0;',
  '  white-space: pre-wrap;',
  '}',
  '.smd-heading-1 { font-size: 28px; font-weight: 350; line-height: 36px; margin: 24px 0 0; }',
  '.smd-heading-2 { font-size: 24px; font-weight: 380; line-height: 28px; margin: 24px 0 0; }',
  '.smd-heading-3, .smd-heading-4, .smd-heading-5, .smd-heading-6 { font-size: 20px; font-weight: 470; line-height: 24px; margin: 24px 0 -8px; }',
  '.smd-heading-1 + .smd-heading-2 { margin-top: 8px; }',
  '.smd-heading-2 + .smd-heading-3,',
  '.smd-heading-3 + .smd-heading-4,',
  '.smd-heading-4 + .smd-heading-5,',
  '.smd-heading-5 + .smd-heading-6 { margin-top: 0; }',
  '.smd-link {',
  '  color: rgb(230, 230, 230);',
  '  text-decoration-line: underline;',
  '  text-decoration-style: dotted;',
  '  text-decoration-thickness: 1.36px;',
  '  text-decoration-color: rgb(230, 230, 230);',
  '  text-underline-offset: 3.91px;',
  '}',
  '.smd-link:hover { color: #ffffff; text-decoration-color: #ffffff; }',
  '.smd-rich-resource-group { margin: 32px 0; white-space: normal; }',
  '.smd-inline-code {',
  '  display: inline;',
  '  border-radius: 9999px;',
  '  background: rgb(23, 23, 23);',
  '  color: rgba(255, 255, 255, 0.55);',
  '  font-family: "Google Sans Code", ui-monospace, SFMono-Regular, Consolas, monospace;',
  '  font-size: 15px;',
  '  font-weight: 400;',
  '  line-height: 20px;',
  '  padding: 4px 6px;',
  '  white-space: break-spaces;',
  '}',
  '.smd-list {',
  '  display: block;',
  '  margin: 0;',
  '  padding: 0 0 0 3.36px;',
  '  list-style: none;',
  '}',
  '.smd-list-ordered { padding-left: 4px; }',
  '.smd-list > li {',
  '  position: relative;',
  '  margin: 0;',
  '  padding: 0 0 0 36px;',
  '  list-style: none;',
  '}',
  '.smd-list > li + li { margin-top: 12px; }',
  '.smd-list-unordered > li::before {',
  '  position: absolute;',
  '  top: 7.5px;',
  '  left: 0;',
  '  width: 9px;',
  '  height: 9px;',
  '  background: currentColor;',
  '  content: "";',
  '  -webkit-mask-image: url("data:image/svg+xml,%3Csvg width=%229%22 height=%229%22 viewBox=%220 0 9 9%22 fill=%22none%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Ccircle cx=%224.2998%22 cy=%224.30005%22 r=%223.65%22 stroke=%22currentColor%22 stroke-width=%221.3%22/%3E%3C/svg%3E");',
  '  mask-image: url("data:image/svg+xml,%3Csvg width=%229%22 height=%229%22 viewBox=%220 0 9 9%22 fill=%22none%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Ccircle cx=%224.2998%22 cy=%224.30005%22 r=%223.65%22 stroke=%22currentColor%22 stroke-width=%221.3%22/%3E%3C/svg%3E");',
  '  -webkit-mask-repeat: no-repeat;',
  '  mask-repeat: no-repeat;',
  '  -webkit-mask-size: contain;',
  '  mask-size: contain;',
  '}',
  '.smd-list-ordered > li { counter-increment: smd-list-item; }',
  '.smd-list-ordered > li::before {',
  '  position: absolute;',
  '  top: 0;',
  '  left: 0;',
  '  width: 24px;',
  '  height: 24px;',
  '  content: counter(smd-list-item) ".";',
  '}',
  '.smd-list .smd-list-ordered > li::before { content: counter(smd-list-item, lower-alpha) "."; }',
  '.smd-list .smd-list-ordered .smd-list-ordered > li::before { content: counter(smd-list-item, lower-roman) "."; }',
  '.smd-list-content {',
  '  display: flex;',
  '  min-width: 0;',
  '  flex-direction: column;',
  '  gap: 0;',
  '}',
  '.smd-list-content > .smd-paragraph { padding-left: 4px; }',
  '.smd-list-content > .smd-list { margin-top: 12px; }',
  '.smd-task-item::before { display: none !important; }',
  '.smd-task-box {',
  '  position: absolute;',
  '  top: 3px;',
  '  left: 0;',
  '  display: inline-flex;',
  '  width: 18px;',
  '  height: 18px;',
  '  align-items: center;',
  '  justify-content: center;',
  '  border: 1px solid rgba(227, 227, 227, 0.55);',
  '  border-radius: 4px;',
  '  color: rgb(23, 23, 23);',
  '}',
  '.smd-task-box[data-checked="true"] { background: rgb(227, 227, 227); }',
  '.smd-blockquote { display: block; margin: 0; padding: 0; border: 0; color: inherit; }',
  '.smd-hr {',
  '  width: 100%;',
  '  height: 1px;',
  '  margin: 8px 0;',
  '  border: 0;',
  '  background: rgba(255, 255, 255, 0.12);',
  '}',
  '.smd-math-inline {',
  '  display: inline;',
  '  vertical-align: baseline;',
  '}',
  '.smd-math-display {',
  '  width: 100%;',
  '  max-width: 100%;',
  '  overflow: auto;',
  '  padding: 0;',
  '  text-align: start;',
  '}',
  '.smd-math-display .katex-display { margin: 24px 0; text-align: center; }',
  '.smd-math-display .katex { font-size: 24px; line-height: 1.2; }',
  '.smd-math-error {',
  '  color: #ffb4ab;',
  '  font-family: "Google Sans Code", ui-monospace, monospace;',
  '  font-size: 15px;',
  '}',
  '.smd-code-block {',
  '  position: relative;',
  '  min-width: 0;',
  '  margin: 16px -16px 0;',
  '  overflow: clip;',
  '  border-radius: 40px;',
  '  background: rgb(23, 23, 23);',
  '  padding: 26px 0 32px 32px;',
  '}',
  '.smd-code-header {',
  '  position: sticky;',
  '  top: 0;',
  '  z-index: 2;',
  '  display: flex;',
  '  width: 100%;',
  '  height: 36px;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  background: rgb(23, 23, 23);',
  '  padding: 0 11px 0 0;',
  '  color: rgb(255, 255, 255);',
  '}',
  '.smd-code-language {',
  '  font-family: "Google Sans Flex", "Google Sans", "Helvetica Neue", sans-serif;',
  '  font-size: 15px;',
  '  font-weight: 540;',
  '  line-height: 20px;',
  '}',
  '.smd-code-buttons { display: flex; width: 72px; height: 36px; }',
  '.smd-icon-button {',
  '  display: inline-flex;',
  '  width: 36px;',
  '  height: 36px;',
  '  flex: 0 0 36px;',
  '  align-items: center;',
  '  justify-content: center;',
  '  border: 0;',
  '  border-radius: 9999px;',
  '  background: transparent;',
  '  color: rgb(255, 255, 255);',
  '  cursor: pointer;',
  '  padding: 6px;',
  '}',
  '.smd-icon-button:hover { background: rgba(255, 255, 255, 0.08); }',
  '.smd-icon-button:focus-visible { outline: 2px solid rgba(138, 180, 248, 0.9); outline-offset: 1px; }',
  '.smd-code-scroll { width: 100%; overflow: auto; }',
  '.smd-code-pre {',
  '  width: 100%;',
  '  margin: 0;',
  '  padding: 0;',
  '  overflow: visible;',
  '  background: transparent;',
  '  white-space: pre;',
  '}',
  '.smd-code-pre code {',
  '  display: block;',
  '  min-width: max-content;',
  '  padding: 16px 32px 0 0;',
  '  background: transparent;',
  '  color: rgb(255, 255, 255);',
  '  font-family: "Google Sans Code", ui-monospace, SFMono-Regular, Consolas, monospace;',
  '  font-size: 14px;',
  '  font-weight: 400;',
  '  line-height: 21px;',
  '  tab-size: 4;',
  '}',
  '.smd-code-block .hljs { color: rgb(255, 255, 255); background: transparent; }',
  '.smd-code-block .hljs-comment, .smd-code-block .hljs-quote { color: rgb(128, 128, 128); }',
  '.smd-code-block .hljs-keyword, .smd-code-block .hljs-selector-id, .smd-code-block .hljs-selector-class { color: rgb(150, 157, 255); }',
  '.smd-code-block .hljs-string, .smd-code-block .hljs-regexp, .smd-code-block .hljs-addition, .smd-code-block .hljs-template-tag { color: rgb(96, 214, 115); }',
  '.smd-code-block .hljs-number, .smd-code-block .hljs-literal, .smd-code-block .hljs-attr, .smd-code-block .hljs-variable, .smd-code-block .hljs-template-variable { color: rgb(255, 150, 218); }',
  '.smd-code-block .hljs-title, .smd-code-block .hljs-title.function_, .smd-code-block .hljs-section { color: rgb(255, 219, 15); }',
  '.smd-code-block .hljs-name, .smd-code-block .hljs-selector-tag { color: rgb(79, 160, 255); }',
  '.smd-code-block .hljs-meta, .smd-code-block .hljs-built_in, .smd-code-block .hljs-builtin-name, .smd-code-block .hljs-deletion { color: rgb(255, 90, 89); }',
  '.smd-code-block .hljs-meta .hljs-keyword { color: rgb(255, 90, 89); font-weight: 700; }',
  '.smd-svg-preview-block {',
  '  width: 100%;',
  '  min-width: 0;',
  '  overflow: hidden;',
  '  box-sizing: border-box;',
  '  border: 0.8px solid rgb(68, 71, 70);',
  '  border-radius: 12px;',
  '  background: transparent;',
  '  color: rgb(196, 199, 197);',
  '}',
  '.smd-svg-preview-toolbar {',
  '  display: flex;',
  '  width: 100%;',
  '  height: 56px;',
  '  box-sizing: border-box;',
  '  align-items: center;',
  '  justify-content: space-between;',
  '  background: rgb(30, 31, 32);',
  '  padding: 8px 8px 8px 16px;',
  '}',
  '.smd-svg-preview-label {',
  '  color: rgb(196, 199, 197);',
  '  font-family: "Google Sans Flex", "Google Sans", "Helvetica Neue", sans-serif;',
  '  font-size: 14px;',
  '  font-weight: 500;',
  '  line-height: 24px;',
  '}',
  '.smd-svg-preview-actions { display: flex; height: 40px; gap: 4px; }',
  '.smd-svg-preview-button {',
  '  display: inline-flex;',
  '  width: 40px;',
  '  height: 40px;',
  '  flex: 0 0 40px;',
  '  align-items: center;',
  '  justify-content: center;',
  '  border: 0;',
  '  border-radius: 9999px;',
  '  background: transparent;',
  '  color: rgb(196, 199, 197);',
  '  cursor: pointer;',
  '  padding: 8px;',
  '}',
  '.smd-svg-preview-button:hover { background: rgba(255, 255, 255, 0.08); }',
  '.smd-svg-preview-button:focus-visible { outline: 2px solid rgba(138, 180, 248, 0.9); outline-offset: 1px; }',
  '.smd-svg-preview-canvas { width: 100%; height: 400px; background: rgb(19, 19, 20); }',
  '.smd-svg-preview-frame { display: block; width: 100%; height: 100%; border: 0; background: transparent; }',
  '.smd-table-block { position: relative; width: 100%; min-width: 0; }',
  '.smd-table-content { overflow: auto; padding: 8px 0; }',
  '.smd-table-block.has-scrollbar .smd-table-content {',
  '  -webkit-mask-image: linear-gradient(90deg, rgba(0, 0, 0, 0.2), #000 48px, #000 calc(100% - 48px), rgba(0, 0, 0, 0.2));',
  '  mask-image: linear-gradient(90deg, rgba(0, 0, 0, 0.2), #000 48px, #000 calc(100% - 48px), rgba(0, 0, 0, 0.2));',
  '}',
  '.smd-table-block.has-scrollbar.is-at-scroll-start .smd-table-content {',
  '  -webkit-mask-image: linear-gradient(90deg, #000, #000 calc(100% - 48px), rgba(0, 0, 0, 0.2));',
  '  mask-image: linear-gradient(90deg, #000, #000 calc(100% - 48px), rgba(0, 0, 0, 0.2));',
  '}',
  '.smd-table-block.has-scrollbar.is-at-scroll-end .smd-table-content {',
  '  -webkit-mask-image: linear-gradient(90deg, rgba(0, 0, 0, 0.2), #000 48px, #000);',
  '  mask-image: linear-gradient(90deg, rgba(0, 0, 0, 0.2), #000 48px, #000);',
  '}',
  '.smd-table { width: 100%; min-width: max-content; border-collapse: separate; border-spacing: 0; }',
  '.smd-table th, .smd-table td {',
  '  position: relative;',
  '  width: 173px;',
  '  min-width: 173px;',
  '  max-width: 320px;',
  '  vertical-align: top;',
  '  color: rgb(227, 227, 227);',
  '  font: inherit;',
  '  font-weight: 400;',
  '  text-align: left;',
  '  white-space: normal;',
  '}',
  '.smd-table th { padding: 12px 12px 16px; }',
  '.smd-table td { padding: 16px 12px; }',
  '.smd-table th:first-child { padding-left: 0; }',
  '.smd-table th:last-child { padding-right: 0; }',
  '.smd-table td:first-child { padding-left: 0; }',
  '.smd-table td:last-child { padding-right: 0; }',
  '.smd-table thead th::after,',
  '.smd-table tbody tr:not(:last-child) > td::after {',
  '  position: absolute;',
  '  right: 12px;',
  '  bottom: 0;',
  '  left: 12px;',
  '  height: 1px;',
  '  background: rgba(255, 255, 255, 0.12);',
  '  content: "";',
  '}',
  '.smd-table tr > :first-child::after { left: 0; }',
  '.smd-table tr > :last-child::after { right: 0; }',
  '.smd-table-footer {',
  '  position: relative;',
  '  display: flex;',
  '  height: 20px;',
  '  align-items: center;',
  '  justify-content: flex-start;',
  '  margin-top: 10px;',
  '}',
  '.smd-table-menu-trigger {',
  '  display: inline-flex;',
  '  width: 32px;',
  '  height: 20px;',
  '  align-items: center;',
  '  justify-content: center;',
  '  border: 0;',
  '  border-radius: 9999px;',
  '  background: rgb(23, 23, 23);',
  '  color: rgb(230, 230, 230);',
  '  cursor: pointer;',
  '  padding: 0;',
  '}',
  '.smd-table-menu-trigger:hover { background: rgb(42, 42, 42); }',
  '.smd-table-menu {',
  '  position: absolute;',
  '  top: 28px;',
  '  left: 0;',
  '  z-index: 20;',
  '  width: 188px;',
  '  height: 96px;',
  '  box-sizing: border-box;',
  '  overflow: hidden;',
  '  border: 0;',
  '  border-radius: 20px;',
  '  background: rgb(31, 31, 31);',
  '  box-shadow: none;',
  '  padding: 8px;',
  '}',
  '.smd-table-menu button {',
  '  display: flex;',
  '  width: 100%;',
  '  height: 40px;',
  '  align-items: center;',
  '  gap: 8px;',
  '  border: 0;',
  '  border-radius: 12px;',
  '  background: transparent;',
  '  color: rgb(230, 230, 230);',
  '  cursor: pointer;',
  '  font: inherit;',
  '  font-size: 13px;',
  '  line-height: 17px;',
  '  padding: 0 8px;',
  '  text-align: left;',
  '}',
  '.smd-table-menu button:hover { background: rgba(255, 255, 255, 0.08); }',
  '.smd-media-gallery {',
  '  display: grid;',
  '  width: 100%;',
  '  grid-template-columns: repeat(2, minmax(0, 1fr));',
  '  gap: 8px;',
  '}',
  '.smd-media-gallery[data-count="1"] { grid-template-columns: minmax(0, 1fr); }',
  '.smd-media-card {',
  '  display: block;',
  '  width: 100%;',
  '  min-width: 0;',
  '  border: 0;',
  '  background: transparent;',
  '  color: inherit;',
  '  cursor: pointer;',
  '  padding: 0;',
  '  text-align: left;',
  '}',
  '.smd-media-frame {',
  '  position: relative;',
  '  width: 100%;',
  '  aspect-ratio: var(--smd-media-ratio, 4 / 3);',
  '  min-height: 148px;',
  '  overflow: hidden;',
  '  border: 1px solid rgba(255, 255, 255, 0.07);',
  '  border-radius: 16px;',
  '  background: rgb(23, 23, 23);',
  '}',
  '.smd-media-card:hover .smd-media-frame { border-color: rgba(255, 255, 255, 0.18); }',
  '.smd-media-frame img, .smd-media-frame video {',
  '  position: absolute;',
  '  inset: 0;',
  '  width: 100%;',
  '  height: 100%;',
  '  object-fit: cover;',
  '}',
  '.smd-media-loading {',
  '  position: absolute;',
  '  inset: 0;',
  '  overflow: hidden;',
  '  background: radial-gradient(circle at 28% 25%, #b4bac7 0, #767d8c 30%, #1b1e25 67%, #0d0f14 100%);',
  '}',
  '.smd-media-loading::before, .smd-media-loading::after {',
  '  position: absolute;',
  '  width: 72%;',
  '  height: 72%;',
  '  border-radius: 50%;',
  '  filter: blur(18px);',
  '  content: "";',
  '  animation: smd-media-drift 8s ease-in-out infinite;',
  '}',
  '.smd-media-loading::before { top: -25%; left: -15%; background: rgba(235, 239, 247, 0.5); }',
  '.smd-media-loading::after { right: -18%; bottom: -25%; background: rgba(10, 12, 17, 0.88); animation-delay: -4s; }',
  '.smd-media-error {',
  '  position: absolute;',
  '  inset: 0;',
  '  display: flex;',
  '  flex-direction: column;',
  '  align-items: flex-start;',
  '  justify-content: flex-start;',
  '  gap: 8px;',
  '  background: linear-gradient(180deg, #232323, #171717);',
  '  color: rgb(227, 227, 227);',
  '  padding: 18px;',
  '}',
  '.smd-media-error-title { font-size: 15px; font-weight: 540; }',
  '.smd-media-error-detail { color: rgb(196, 199, 197); font-size: 13px; line-height: 18px; }',
  '.smd-inline-image {',
  '  display: inline-block;',
  '  max-width: 100%;',
  '  max-height: 360px;',
  '  border-radius: 12px;',
  '  object-fit: cover;',
  '  vertical-align: middle;',
  '}',
  '.smd-footnotes {',
  '  display: flex;',
  '  flex-direction: column;',
  '  gap: 12px;',
  '  border-top: 1px solid rgba(255, 255, 255, 0.12);',
  '  color: rgb(196, 199, 197);',
  '  font-size: 14px;',
  '  line-height: 20px;',
  '  padding-top: 16px;',
  '}',
  '.smd-footnotes ol { margin: 0; padding-left: 24px; }',
  '.smd-footnote-ref { font-size: 12px; line-height: 1; vertical-align: super; }',
  '.smd-scroll { scrollbar-width: auto; scrollbar-color: auto; }',
  '.smd-scroll::-webkit-scrollbar, .smd-scroll::-webkit-scrollbar-corner { width: 12px; height: 12px; background: transparent; }',
  '.smd-scroll::-webkit-scrollbar-track { background: transparent; }',
  '.smd-scroll::-webkit-scrollbar-thumb { min-width: 48px; min-height: 48px; border: 2px solid transparent; border-radius: 9999px; background: transparent; background-clip: content-box; }',
  '.smd-scroll:hover::-webkit-scrollbar-thumb { background-color: #333537; background-clip: content-box; }',
  '.smd-scroll::-webkit-scrollbar-thumb:hover, .smd-scroll::-webkit-scrollbar-thumb:active { background-color: #444746; background-clip: content-box; }',
  '.smd-scroll::-webkit-scrollbar-button { width: 0; height: 0; }',
  '@media (max-width: 640px) {',
  '  .smd-code-block { margin: 8px 0 0; border-radius: 28px; padding: 20px 0 24px 20px; }',
  '  .smd-code-pre code { padding-right: 20px; }',
  '  .smd-media-gallery { grid-template-columns: minmax(0, 1fr); }',
  '  .smd-table-block { width: 100%; }',
  '  .smd-table th, .smd-table td { min-width: 132px; }',
  '}',
  '@media (prefers-reduced-motion: reduce) {',
  '  .smd-streaming .smd-w, .smd-streaming .smd-h, .smd-streaming .smd-code-block,',
  '  .smd-streaming .smd-table-block, .smd-streaming .smd-media-gallery, .smd-streaming .smd-math-display { animation: none !important; }',
  '  .smd-media-loading::before, .smd-media-loading::after { animation: none !important; }',
  '}',
].join('\n');

function useInjectStyles() {
  useInsertionEffect(() => {
    if (typeof document === 'undefined' || document.getElementById(STYLE_ID)) return;
    const element = document.createElement('style');
    element.id = STYLE_ID;
    element.textContent = STYLE_CSS;
    document.head.appendChild(element);
  }, []);
}

export { useInjectStyles };
